// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: server_v1/dag.proto

package server_v1

import (
	common "github.com/rendau/loom/api/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DagMain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	ImageDigest   string                 `protobuf:"bytes,3,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	Schedule      string                 `protobuf:"bytes,4,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Paused        bool                   `protobuf:"varint,5,opt,name=paused,proto3" json:"paused,omitempty"`
	SdkVersion    string                 `protobuf:"bytes,6,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	Tasks         []*DagTaskMain         `protobuf:"bytes,7,rep,name=tasks,proto3" json:"tasks,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ModifiedAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=modified_at,json=modifiedAt,proto3,oneof" json:"modified_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DagMain) Reset() {
	*x = DagMain{}
	mi := &file_server_v1_dag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DagMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DagMain) ProtoMessage() {}

func (x *DagMain) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_dag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DagMain.ProtoReflect.Descriptor instead.
func (*DagMain) Descriptor() ([]byte, []int) {
	return file_server_v1_dag_proto_rawDescGZIP(), []int{0}
}

func (x *DagMain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DagMain) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *DagMain) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

func (x *DagMain) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *DagMain) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

func (x *DagMain) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *DagMain) GetTasks() []*DagTaskMain {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *DagMain) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DagMain) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

type DagTaskMain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DependsOn     []*DagTaskDepMain      `protobuf:"bytes,2,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DagTaskMain) Reset() {
	*x = DagTaskMain{}
	mi := &file_server_v1_dag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DagTaskMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DagTaskMain) ProtoMessage() {}

func (x *DagTaskMain) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_dag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DagTaskMain.ProtoReflect.Descriptor instead.
func (*DagTaskMain) Descriptor() ([]byte, []int) {
	return file_server_v1_dag_proto_rawDescGZIP(), []int{1}
}

func (x *DagTaskMain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DagTaskMain) GetDependsOn() []*DagTaskDepMain {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

type DagTaskDepMain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          string                 `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Streamed      bool                   `protobuf:"varint,2,opt,name=streamed,proto3" json:"streamed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DagTaskDepMain) Reset() {
	*x = DagTaskDepMain{}
	mi := &file_server_v1_dag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DagTaskDepMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DagTaskDepMain) ProtoMessage() {}

func (x *DagTaskDepMain) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_dag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DagTaskDepMain.ProtoReflect.Descriptor instead.
func (*DagTaskDepMain) Descriptor() ([]byte, []int) {
	return file_server_v1_dag_proto_rawDescGZIP(), []int{2}
}

func (x *DagTaskDepMain) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *DagTaskDepMain) GetStreamed() bool {
	if x != nil {
		return x.Streamed
	}
	return false
}

type DagRegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DagRegisterReq) Reset() {
	*x = DagRegisterReq{}
	mi := &file_server_v1_dag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DagRegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DagRegisterReq) ProtoMessage() {}

func (x *DagRegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_dag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DagRegisterReq.ProtoReflect.Descriptor instead.
func (*DagRegisterReq) Descriptor() ([]byte, []int) {
	return file_server_v1_dag_proto_rawDescGZIP(), []int{3}
}

func (x *DagRegisterReq) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type DagRegisterRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dag           *DagMain               `protobuf:"bytes,1,opt,name=dag,proto3" json:"dag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DagRegisterRep) Reset() {
	*x = DagRegisterRep{}
	mi := &file_server_v1_dag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DagRegisterRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DagRegisterRep) ProtoMessage() {}

func (x *DagRegisterRep) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_dag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DagRegisterRep.ProtoReflect.Descriptor instead.
func (*DagRegisterRep) Descriptor() ([]byte, []int) {
	return file_server_v1_dag_proto_rawDescGZIP(), []int{4}
}

func (x *DagRegisterRep) GetDag() *DagMain {
	if x != nil {
		return x.Dag
	}
	return nil
}

type DagListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListParams    *common.ListParamsSt   `protobuf:"bytes,1,opt,name=list_params,json=listParams,proto3" json:"list_params,omitempty"`
	Paused        *bool                  `protobuf:"varint,2,opt,name=paused,proto3,oneof" json:"paused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DagListReq) Reset() {
	*x = DagListReq{}
	mi := &file_server_v1_dag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DagListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DagListReq) ProtoMessage() {}

func (x *DagListReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_dag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DagListReq.ProtoReflect.Descriptor instead.
func (*DagListReq) Descriptor() ([]byte, []int) {
	return file_server_v1_dag_proto_rawDescGZIP(), []int{5}
}

func (x *DagListReq) GetListParams() *common.ListParamsSt {
	if x != nil {
		return x.ListParams
	}
	return nil
}

func (x *DagListReq) GetPaused() bool {
	if x != nil && x.Paused != nil {
		return *x.Paused
	}
	return false
}

type DagListRep struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	PaginationInfo *common.PaginationInfoSt `protobuf:"bytes,1,opt,name=pagination_info,json=paginationInfo,proto3" json:"pagination_info,omitempty"`
	Results        []*DagMain               `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DagListRep) Reset() {
	*x = DagListRep{}
	mi := &file_server_v1_dag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DagListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DagListRep) ProtoMessage() {}

func (x *DagListRep) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_dag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DagListRep.ProtoReflect.Descriptor instead.
func (*DagListRep) Descriptor() ([]byte, []int) {
	return file_server_v1_dag_proto_rawDescGZIP(), []int{6}
}

func (x *DagListRep) GetPaginationInfo() *common.PaginationInfoSt {
	if x != nil {
		return x.PaginationInfo
	}
	return nil
}

func (x *DagListRep) GetResults() []*DagMain {
	if x != nil {
		return x.Results
	}
	return nil
}

type DagGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DagGetReq) Reset() {
	*x = DagGetReq{}
	mi := &file_server_v1_dag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DagGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DagGetReq) ProtoMessage() {}

func (x *DagGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_dag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DagGetReq.ProtoReflect.Descriptor instead.
func (*DagGetReq) Descriptor() ([]byte, []int) {
	return file_server_v1_dag_proto_rawDescGZIP(), []int{7}
}

func (x *DagGetReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DagSetPausedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Paused        bool                   `protobuf:"varint,2,opt,name=paused,proto3" json:"paused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DagSetPausedReq) Reset() {
	*x = DagSetPausedReq{}
	mi := &file_server_v1_dag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DagSetPausedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DagSetPausedReq) ProtoMessage() {}

func (x *DagSetPausedReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_dag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DagSetPausedReq.ProtoReflect.Descriptor instead.
func (*DagSetPausedReq) Descriptor() ([]byte, []int) {
	return file_server_v1_dag_proto_rawDescGZIP(), []int{8}
}

func (x *DagSetPausedReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DagSetPausedReq) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

type DagDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DagDeleteReq) Reset() {
	*x = DagDeleteReq{}
	mi := &file_server_v1_dag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DagDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DagDeleteReq) ProtoMessage() {}

func (x *DagDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_dag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DagDeleteReq.ProtoReflect.Descriptor instead.
func (*DagDeleteReq) Descriptor() ([]byte, []int) {
	return file_server_v1_dag_proto_rawDescGZIP(), []int{9}
}

func (x *DagDeleteReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_server_v1_dag_proto protoreflect.FileDescriptor

const file_server_v1_dag_proto_rawDesc = "" +
	"\n" +
	"\x13server_v1/dag.proto\x12\tserver_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\xe6\x02\n" +
	"\aDagMain\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12!\n" +
	"\fimage_digest\x18\x03 \x01(\tR\vimageDigest\x12\x1a\n" +
	"\bschedule\x18\x04 \x01(\tR\bschedule\x12\x16\n" +
	"\x06paused\x18\x05 \x01(\bR\x06paused\x12\x1f\n" +
	"\vsdk_version\x18\x06 \x01(\tR\n" +
	"sdkVersion\x12,\n" +
	"\x05tasks\x18\a \x03(\v2\x16.server_v1.DagTaskMainR\x05tasks\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12@\n" +
	"\vmodified_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"modifiedAt\x88\x01\x01B\x0e\n" +
	"\f_modified_at\"[\n" +
	"\vDagTaskMain\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x128\n" +
	"\n" +
	"depends_on\x18\x02 \x03(\v2\x19.server_v1.DagTaskDepMainR\tdependsOn\"@\n" +
	"\x0eDagTaskDepMain\x12\x12\n" +
	"\x04task\x18\x01 \x01(\tR\x04task\x12\x1a\n" +
	"\bstreamed\x18\x02 \x01(\bR\bstreamed\"&\n" +
	"\x0eDagRegisterReq\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\"6\n" +
	"\x0eDagRegisterRep\x12$\n" +
	"\x03dag\x18\x01 \x01(\v2\x12.server_v1.DagMainR\x03dag\"k\n" +
	"\n" +
	"DagListReq\x125\n" +
	"\vlist_params\x18\x01 \x01(\v2\x14.common.ListParamsStR\n" +
	"listParams\x12\x1b\n" +
	"\x06paused\x18\x02 \x01(\bH\x00R\x06paused\x88\x01\x01B\t\n" +
	"\a_paused\"}\n" +
	"\n" +
	"DagListRep\x12A\n" +
	"\x0fpagination_info\x18\x01 \x01(\v2\x18.common.PaginationInfoStR\x0epaginationInfo\x12,\n" +
	"\aresults\x18\x02 \x03(\v2\x12.server_v1.DagMainR\aresults\"\x1f\n" +
	"\tDagGetReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"=\n" +
	"\x0fDagSetPausedReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06paused\x18\x02 \x01(\bR\x06paused\"\"\n" +
	"\fDagDeleteReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\xa8\x03\n" +
	"\n" +
	"DagService\x12T\n" +
	"\vRegisterDag\x12\x19.server_v1.DagRegisterReq\x1a\x19.server_v1.DagRegisterRep\"\x0f\x82\xd3\xe4\x93\x02\t:\x01*\"\x04/dag\x12E\n" +
	"\aListDag\x12\x15.server_v1.DagListReq\x1a\x15.server_v1.DagListRep\"\f\x82\xd3\xe4\x93\x02\x06\x12\x04/dag\x12G\n" +
	"\x06GetDag\x12\x14.server_v1.DagGetReq\x1a\x12.server_v1.DagMain\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/dag/{name}\x12a\n" +
	"\fSetDagPaused\x12\x1a.server_v1.DagSetPausedReq\x1a\x16.google.protobuf.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\x1a\x12/dag/{name}/paused\x12Q\n" +
	"\tDeleteDag\x12\x17.server_v1.DagDeleteReq\x1a\x16.google.protobuf.Empty\"\x13\x82\xd3\xe4\x93\x02\r*\v/dag/{name}B0Z.github.com/rendau/loom/api/server_v1;server_v1b\x06proto3"

var (
	file_server_v1_dag_proto_rawDescOnce sync.Once
	file_server_v1_dag_proto_rawDescData []byte
)

func file_server_v1_dag_proto_rawDescGZIP() []byte {
	file_server_v1_dag_proto_rawDescOnce.Do(func() {
		file_server_v1_dag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_v1_dag_proto_rawDesc), len(file_server_v1_dag_proto_rawDesc)))
	})
	return file_server_v1_dag_proto_rawDescData
}

var file_server_v1_dag_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_server_v1_dag_proto_goTypes = []any{
	(*DagMain)(nil),                 // 0: server_v1.DagMain
	(*DagTaskMain)(nil),             // 1: server_v1.DagTaskMain
	(*DagTaskDepMain)(nil),          // 2: server_v1.DagTaskDepMain
	(*DagRegisterReq)(nil),          // 3: server_v1.DagRegisterReq
	(*DagRegisterRep)(nil),          // 4: server_v1.DagRegisterRep
	(*DagListReq)(nil),              // 5: server_v1.DagListReq
	(*DagListRep)(nil),              // 6: server_v1.DagListRep
	(*DagGetReq)(nil),               // 7: server_v1.DagGetReq
	(*DagSetPausedReq)(nil),         // 8: server_v1.DagSetPausedReq
	(*DagDeleteReq)(nil),            // 9: server_v1.DagDeleteReq
	(*timestamppb.Timestamp)(nil),   // 10: google.protobuf.Timestamp
	(*common.ListParamsSt)(nil),     // 11: common.ListParamsSt
	(*common.PaginationInfoSt)(nil), // 12: common.PaginationInfoSt
	(*emptypb.Empty)(nil),           // 13: google.protobuf.Empty
}
var file_server_v1_dag_proto_depIdxs = []int32{
	1,  // 0: server_v1.DagMain.tasks:type_name -> server_v1.DagTaskMain
	10, // 1: server_v1.DagMain.created_at:type_name -> google.protobuf.Timestamp
	10, // 2: server_v1.DagMain.modified_at:type_name -> google.protobuf.Timestamp
	2,  // 3: server_v1.DagTaskMain.depends_on:type_name -> server_v1.DagTaskDepMain
	0,  // 4: server_v1.DagRegisterRep.dag:type_name -> server_v1.DagMain
	11, // 5: server_v1.DagListReq.list_params:type_name -> common.ListParamsSt
	12, // 6: server_v1.DagListRep.pagination_info:type_name -> common.PaginationInfoSt
	0,  // 7: server_v1.DagListRep.results:type_name -> server_v1.DagMain
	3,  // 8: server_v1.DagService.RegisterDag:input_type -> server_v1.DagRegisterReq
	5,  // 9: server_v1.DagService.ListDag:input_type -> server_v1.DagListReq
	7,  // 10: server_v1.DagService.GetDag:input_type -> server_v1.DagGetReq
	8,  // 11: server_v1.DagService.SetDagPaused:input_type -> server_v1.DagSetPausedReq
	9,  // 12: server_v1.DagService.DeleteDag:input_type -> server_v1.DagDeleteReq
	4,  // 13: server_v1.DagService.RegisterDag:output_type -> server_v1.DagRegisterRep
	6,  // 14: server_v1.DagService.ListDag:output_type -> server_v1.DagListRep
	0,  // 15: server_v1.DagService.GetDag:output_type -> server_v1.DagMain
	13, // 16: server_v1.DagService.SetDagPaused:output_type -> google.protobuf.Empty
	13, // 17: server_v1.DagService.DeleteDag:output_type -> google.protobuf.Empty
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_server_v1_dag_proto_init() }
func file_server_v1_dag_proto_init() {
	if File_server_v1_dag_proto != nil {
		return
	}
	file_server_v1_dag_proto_msgTypes[0].OneofWrappers = []any{}
	file_server_v1_dag_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_v1_dag_proto_rawDesc), len(file_server_v1_dag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_v1_dag_proto_goTypes,
		DependencyIndexes: file_server_v1_dag_proto_depIdxs,
		MessageInfos:      file_server_v1_dag_proto_msgTypes,
	}.Build()
	File_server_v1_dag_proto = out.File
	file_server_v1_dag_proto_goTypes = nil
	file_server_v1_dag_proto_depIdxs = nil
}
