// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: server_v1/dashboard.proto

package server_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DashboardRep struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	ActiveRuns     int64                   `protobuf:"varint,1,opt,name=active_runs,json=activeRuns,proto3" json:"active_runs,omitempty"`
	DagCount       int64                   `protobuf:"varint,2,opt,name=dag_count,json=dagCount,proto3" json:"dag_count,omitempty"`
	PausedDagCount int64                   `protobuf:"varint,3,opt,name=paused_dag_count,json=pausedDagCount,proto3" json:"paused_dag_count,omitempty"`
	Last_24H       *DashboardWindow        `protobuf:"bytes,4,opt,name=last_24h,json=last24h,proto3" json:"last_24h,omitempty"`
	Last_7D        *DashboardWindow        `protobuf:"bytes,5,opt,name=last_7d,json=last7d,proto3" json:"last_7d,omitempty"`
	Upcoming       []*DashboardUpcoming    `protobuf:"bytes,6,rep,name=upcoming,proto3" json:"upcoming,omitempty"`                                   // ближайшие запуски по cron
	Pools          []*DashboardPool        `protobuf:"bytes,7,rep,name=pools,proto3" json:"pools,omitempty"`                                         // занятость пулов слотов
	RecentFailures []*DashboardFailure     `protobuf:"bytes,8,rep,name=recent_failures,json=recentFailures,proto3" json:"recent_failures,omitempty"` // последние провалившиеся раны
	Activity       []*DashboardDay         `protobuf:"bytes,9,rep,name=activity,proto3" json:"activity,omitempty"`                                   // раны по дням (14 дней)
	DagDurations   []*DashboardDagDuration `protobuf:"bytes,10,rep,name=dag_durations,json=dagDurations,proto3" json:"dag_durations,omitempty"`      // длительности за 7 дней
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DashboardRep) Reset() {
	*x = DashboardRep{}
	mi := &file_server_v1_dashboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardRep) ProtoMessage() {}

func (x *DashboardRep) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_dashboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardRep.ProtoReflect.Descriptor instead.
func (*DashboardRep) Descriptor() ([]byte, []int) {
	return file_server_v1_dashboard_proto_rawDescGZIP(), []int{0}
}

func (x *DashboardRep) GetActiveRuns() int64 {
	if x != nil {
		return x.ActiveRuns
	}
	return 0
}

func (x *DashboardRep) GetDagCount() int64 {
	if x != nil {
		return x.DagCount
	}
	return 0
}

func (x *DashboardRep) GetPausedDagCount() int64 {
	if x != nil {
		return x.PausedDagCount
	}
	return 0
}

func (x *DashboardRep) GetLast_24H() *DashboardWindow {
	if x != nil {
		return x.Last_24H
	}
	return nil
}

func (x *DashboardRep) GetLast_7D() *DashboardWindow {
	if x != nil {
		return x.Last_7D
	}
	return nil
}

func (x *DashboardRep) GetUpcoming() []*DashboardUpcoming {
	if x != nil {
		return x.Upcoming
	}
	return nil
}

func (x *DashboardRep) GetPools() []*DashboardPool {
	if x != nil {
		return x.Pools
	}
	return nil
}

func (x *DashboardRep) GetRecentFailures() []*DashboardFailure {
	if x != nil {
		return x.RecentFailures
	}
	return nil
}

func (x *DashboardRep) GetActivity() []*DashboardDay {
	if x != nil {
		return x.Activity
	}
	return nil
}

func (x *DashboardRep) GetDagDurations() []*DashboardDagDuration {
	if x != nil {
		return x.DagDurations
	}
	return nil
}

type DashboardWindow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       int64                  `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Failed        int64                  `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardWindow) Reset() {
	*x = DashboardWindow{}
	mi := &file_server_v1_dashboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardWindow) ProtoMessage() {}

func (x *DashboardWindow) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_dashboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardWindow.ProtoReflect.Descriptor instead.
func (*DashboardWindow) Descriptor() ([]byte, []int) {
	return file_server_v1_dashboard_proto_rawDescGZIP(), []int{1}
}

func (x *DashboardWindow) GetSuccess() int64 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *DashboardWindow) GetFailed() int64 {
	if x != nil {
		return x.Failed
	}
	return 0
}

type DashboardUpcoming struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DagName       string                 `protobuf:"bytes,1,opt,name=dag_name,json=dagName,proto3" json:"dag_name,omitempty"`
	NextRunAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=next_run_at,json=nextRunAt,proto3" json:"next_run_at,omitempty"`
	Schedule      string                 `protobuf:"bytes,3,opt,name=schedule,proto3" json:"schedule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardUpcoming) Reset() {
	*x = DashboardUpcoming{}
	mi := &file_server_v1_dashboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardUpcoming) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardUpcoming) ProtoMessage() {}

func (x *DashboardUpcoming) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_dashboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardUpcoming.ProtoReflect.Descriptor instead.
func (*DashboardUpcoming) Descriptor() ([]byte, []int) {
	return file_server_v1_dashboard_proto_rawDescGZIP(), []int{2}
}

func (x *DashboardUpcoming) GetDagName() string {
	if x != nil {
		return x.DagName
	}
	return ""
}

func (x *DashboardUpcoming) GetNextRunAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextRunAt
	}
	return nil
}

func (x *DashboardUpcoming) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

type DashboardPool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Slots         int64                  `protobuf:"varint,2,opt,name=slots,proto3" json:"slots,omitempty"`
	Busy          int64                  `protobuf:"varint,3,opt,name=busy,proto3" json:"busy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardPool) Reset() {
	*x = DashboardPool{}
	mi := &file_server_v1_dashboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardPool) ProtoMessage() {}

func (x *DashboardPool) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_dashboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardPool.ProtoReflect.Descriptor instead.
func (*DashboardPool) Descriptor() ([]byte, []int) {
	return file_server_v1_dashboard_proto_rawDescGZIP(), []int{3}
}

func (x *DashboardPool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DashboardPool) GetSlots() int64 {
	if x != nil {
		return x.Slots
	}
	return 0
}

func (x *DashboardPool) GetBusy() int64 {
	if x != nil {
		return x.Busy
	}
	return 0
}

type DashboardFailure struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	RunId      string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	DagName    string                 `protobuf:"bytes,2,opt,name=dag_name,json=dagName,proto3" json:"dag_name,omitempty"`
	FinishedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	// Первый упавший таск рана и исход его последней попытки — чтобы с
	// дашборда было видно «что именно сломалось» без открытия рана.
	Task          string `protobuf:"bytes,4,opt,name=task,proto3" json:"task,omitempty"`
	ExitReason    string `protobuf:"bytes,5,opt,name=exit_reason,json=exitReason,proto3" json:"exit_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardFailure) Reset() {
	*x = DashboardFailure{}
	mi := &file_server_v1_dashboard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardFailure) ProtoMessage() {}

func (x *DashboardFailure) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_dashboard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardFailure.ProtoReflect.Descriptor instead.
func (*DashboardFailure) Descriptor() ([]byte, []int) {
	return file_server_v1_dashboard_proto_rawDescGZIP(), []int{4}
}

func (x *DashboardFailure) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *DashboardFailure) GetDagName() string {
	if x != nil {
		return x.DagName
	}
	return ""
}

func (x *DashboardFailure) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *DashboardFailure) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *DashboardFailure) GetExitReason() string {
	if x != nil {
		return x.ExitReason
	}
	return ""
}

type DashboardDay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"` // YYYY-MM-DD (UTC)
	Success       int64                  `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Failed        int64                  `protobuf:"varint,3,opt,name=failed,proto3" json:"failed,omitempty"`
	Running       int64                  `protobuf:"varint,4,opt,name=running,proto3" json:"running,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardDay) Reset() {
	*x = DashboardDay{}
	mi := &file_server_v1_dashboard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardDay) ProtoMessage() {}

func (x *DashboardDay) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_dashboard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardDay.ProtoReflect.Descriptor instead.
func (*DashboardDay) Descriptor() ([]byte, []int) {
	return file_server_v1_dashboard_proto_rawDescGZIP(), []int{5}
}

func (x *DashboardDay) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DashboardDay) GetSuccess() int64 {
	if x != nil {
		return x.Success
	}
	return 0
}

func (x *DashboardDay) GetFailed() int64 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *DashboardDay) GetRunning() int64 {
	if x != nil {
		return x.Running
	}
	return 0
}

type DashboardDagDuration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DagName       string                 `protobuf:"bytes,1,opt,name=dag_name,json=dagName,proto3" json:"dag_name,omitempty"`
	AvgSec        float64                `protobuf:"fixed64,2,opt,name=avg_sec,json=avgSec,proto3" json:"avg_sec,omitempty"`
	MaxSec        float64                `protobuf:"fixed64,3,opt,name=max_sec,json=maxSec,proto3" json:"max_sec,omitempty"`
	Runs          int64                  `protobuf:"varint,4,opt,name=runs,proto3" json:"runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DashboardDagDuration) Reset() {
	*x = DashboardDagDuration{}
	mi := &file_server_v1_dashboard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardDagDuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardDagDuration) ProtoMessage() {}

func (x *DashboardDagDuration) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_dashboard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardDagDuration.ProtoReflect.Descriptor instead.
func (*DashboardDagDuration) Descriptor() ([]byte, []int) {
	return file_server_v1_dashboard_proto_rawDescGZIP(), []int{6}
}

func (x *DashboardDagDuration) GetDagName() string {
	if x != nil {
		return x.DagName
	}
	return ""
}

func (x *DashboardDagDuration) GetAvgSec() float64 {
	if x != nil {
		return x.AvgSec
	}
	return 0
}

func (x *DashboardDagDuration) GetMaxSec() float64 {
	if x != nil {
		return x.MaxSec
	}
	return 0
}

func (x *DashboardDagDuration) GetRuns() int64 {
	if x != nil {
		return x.Runs
	}
	return 0
}

var File_server_v1_dashboard_proto protoreflect.FileDescriptor

const file_server_v1_dashboard_proto_rawDesc = "" +
	"\n" +
	"\x19server_v1/dashboard.proto\x12\tserver_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8d\x04\n" +
	"\fDashboardRep\x12\x1f\n" +
	"\vactive_runs\x18\x01 \x01(\x03R\n" +
	"activeRuns\x12\x1b\n" +
	"\tdag_count\x18\x02 \x01(\x03R\bdagCount\x12(\n" +
	"\x10paused_dag_count\x18\x03 \x01(\x03R\x0epausedDagCount\x125\n" +
	"\blast_24h\x18\x04 \x01(\v2\x1a.server_v1.DashboardWindowR\alast24h\x123\n" +
	"\alast_7d\x18\x05 \x01(\v2\x1a.server_v1.DashboardWindowR\x06last7d\x128\n" +
	"\bupcoming\x18\x06 \x03(\v2\x1c.server_v1.DashboardUpcomingR\bupcoming\x12.\n" +
	"\x05pools\x18\a \x03(\v2\x18.server_v1.DashboardPoolR\x05pools\x12D\n" +
	"\x0frecent_failures\x18\b \x03(\v2\x1b.server_v1.DashboardFailureR\x0erecentFailures\x123\n" +
	"\bactivity\x18\t \x03(\v2\x17.server_v1.DashboardDayR\bactivity\x12D\n" +
	"\rdag_durations\x18\n" +
	" \x03(\v2\x1f.server_v1.DashboardDagDurationR\fdagDurations\"C\n" +
	"\x0fDashboardWindow\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\x03R\asuccess\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\x03R\x06failed\"\x86\x01\n" +
	"\x11DashboardUpcoming\x12\x19\n" +
	"\bdag_name\x18\x01 \x01(\tR\adagName\x12:\n" +
	"\vnext_run_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tnextRunAt\x12\x1a\n" +
	"\bschedule\x18\x03 \x01(\tR\bschedule\"M\n" +
	"\rDashboardPool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05slots\x18\x02 \x01(\x03R\x05slots\x12\x12\n" +
	"\x04busy\x18\x03 \x01(\x03R\x04busy\"\xb6\x01\n" +
	"\x10DashboardFailure\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x19\n" +
	"\bdag_name\x18\x02 \x01(\tR\adagName\x12;\n" +
	"\vfinished_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12\x12\n" +
	"\x04task\x18\x04 \x01(\tR\x04task\x12\x1f\n" +
	"\vexit_reason\x18\x05 \x01(\tR\n" +
	"exitReason\"n\n" +
	"\fDashboardDay\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\x03R\asuccess\x12\x16\n" +
	"\x06failed\x18\x03 \x01(\x03R\x06failed\x12\x18\n" +
	"\arunning\x18\x04 \x01(\x03R\arunning\"w\n" +
	"\x14DashboardDagDuration\x12\x19\n" +
	"\bdag_name\x18\x01 \x01(\tR\adagName\x12\x17\n" +
	"\aavg_sec\x18\x02 \x01(\x01R\x06avgSec\x12\x17\n" +
	"\amax_sec\x18\x03 \x01(\x01R\x06maxSec\x12\x12\n" +
	"\x04runs\x18\x04 \x01(\x03R\x04runs2g\n" +
	"\x10DashboardService\x12S\n" +
	"\fGetDashboard\x12\x16.google.protobuf.Empty\x1a\x17.server_v1.DashboardRep\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/dashboardB0Z.github.com/rendau/loom/api/server_v1;server_v1b\x06proto3"

var (
	file_server_v1_dashboard_proto_rawDescOnce sync.Once
	file_server_v1_dashboard_proto_rawDescData []byte
)

func file_server_v1_dashboard_proto_rawDescGZIP() []byte {
	file_server_v1_dashboard_proto_rawDescOnce.Do(func() {
		file_server_v1_dashboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_v1_dashboard_proto_rawDesc), len(file_server_v1_dashboard_proto_rawDesc)))
	})
	return file_server_v1_dashboard_proto_rawDescData
}

var file_server_v1_dashboard_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_server_v1_dashboard_proto_goTypes = []any{
	(*DashboardRep)(nil),          // 0: server_v1.DashboardRep
	(*DashboardWindow)(nil),       // 1: server_v1.DashboardWindow
	(*DashboardUpcoming)(nil),     // 2: server_v1.DashboardUpcoming
	(*DashboardPool)(nil),         // 3: server_v1.DashboardPool
	(*DashboardFailure)(nil),      // 4: server_v1.DashboardFailure
	(*DashboardDay)(nil),          // 5: server_v1.DashboardDay
	(*DashboardDagDuration)(nil),  // 6: server_v1.DashboardDagDuration
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_server_v1_dashboard_proto_depIdxs = []int32{
	1,  // 0: server_v1.DashboardRep.last_24h:type_name -> server_v1.DashboardWindow
	1,  // 1: server_v1.DashboardRep.last_7d:type_name -> server_v1.DashboardWindow
	2,  // 2: server_v1.DashboardRep.upcoming:type_name -> server_v1.DashboardUpcoming
	3,  // 3: server_v1.DashboardRep.pools:type_name -> server_v1.DashboardPool
	4,  // 4: server_v1.DashboardRep.recent_failures:type_name -> server_v1.DashboardFailure
	5,  // 5: server_v1.DashboardRep.activity:type_name -> server_v1.DashboardDay
	6,  // 6: server_v1.DashboardRep.dag_durations:type_name -> server_v1.DashboardDagDuration
	7,  // 7: server_v1.DashboardUpcoming.next_run_at:type_name -> google.protobuf.Timestamp
	7,  // 8: server_v1.DashboardFailure.finished_at:type_name -> google.protobuf.Timestamp
	8,  // 9: server_v1.DashboardService.GetDashboard:input_type -> google.protobuf.Empty
	0,  // 10: server_v1.DashboardService.GetDashboard:output_type -> server_v1.DashboardRep
	10, // [10:11] is the sub-list for method output_type
	9,  // [9:10] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_server_v1_dashboard_proto_init() }
func file_server_v1_dashboard_proto_init() {
	if File_server_v1_dashboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_v1_dashboard_proto_rawDesc), len(file_server_v1_dashboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_v1_dashboard_proto_goTypes,
		DependencyIndexes: file_server_v1_dashboard_proto_depIdxs,
		MessageInfos:      file_server_v1_dashboard_proto_msgTypes,
	}.Build()
	File_server_v1_dashboard_proto = out.File
	file_server_v1_dashboard_proto_goTypes = nil
	file_server_v1_dashboard_proto_depIdxs = nil
}
