// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: server_v1/pool.proto

package server_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PoolService_ListPool_FullMethodName = "/server_v1.PoolService/ListPool"
	PoolService_SetPool_FullMethodName  = "/server_v1.PoolService/SetPool"
)

// PoolServiceClient is the client API for PoolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PoolService — пулы слотов параллелизма (решение №26): таски всех дагов
// конкурируют за слоты своего пула. Удаления нет — на пул могут ссылаться
// манифесты; slots = 0 ставит пул на паузу.
type PoolServiceClient interface {
	ListPool(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PoolListRep, error)
	// SetPool создаёт пул или меняет число слотов существующего.
	SetPool(ctx context.Context, in *PoolSetReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type poolServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPoolServiceClient(cc grpc.ClientConnInterface) PoolServiceClient {
	return &poolServiceClient{cc}
}

func (c *poolServiceClient) ListPool(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PoolListRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PoolListRep)
	err := c.cc.Invoke(ctx, PoolService_ListPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *poolServiceClient) SetPool(ctx context.Context, in *PoolSetReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PoolService_SetPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PoolServiceServer is the server API for PoolService service.
// All implementations must embed UnimplementedPoolServiceServer
// for forward compatibility.
//
// PoolService — пулы слотов параллелизма (решение №26): таски всех дагов
// конкурируют за слоты своего пула. Удаления нет — на пул могут ссылаться
// манифесты; slots = 0 ставит пул на паузу.
type PoolServiceServer interface {
	ListPool(context.Context, *emptypb.Empty) (*PoolListRep, error)
	// SetPool создаёт пул или меняет число слотов существующего.
	SetPool(context.Context, *PoolSetReq) (*emptypb.Empty, error)
	mustEmbedUnimplementedPoolServiceServer()
}

// UnimplementedPoolServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPoolServiceServer struct{}

func (UnimplementedPoolServiceServer) ListPool(context.Context, *emptypb.Empty) (*PoolListRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPool not implemented")
}
func (UnimplementedPoolServiceServer) SetPool(context.Context, *PoolSetReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPool not implemented")
}
func (UnimplementedPoolServiceServer) mustEmbedUnimplementedPoolServiceServer() {}
func (UnimplementedPoolServiceServer) testEmbeddedByValue()                     {}

// UnsafePoolServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PoolServiceServer will
// result in compilation errors.
type UnsafePoolServiceServer interface {
	mustEmbedUnimplementedPoolServiceServer()
}

func RegisterPoolServiceServer(s grpc.ServiceRegistrar, srv PoolServiceServer) {
	// If the following call pancis, it indicates UnimplementedPoolServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PoolService_ServiceDesc, srv)
}

func _PoolService_ListPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).ListPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_ListPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).ListPool(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PoolService_SetPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PoolSetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PoolServiceServer).SetPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PoolService_SetPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PoolServiceServer).SetPool(ctx, req.(*PoolSetReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PoolService_ServiceDesc is the grpc.ServiceDesc for PoolService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PoolService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server_v1.PoolService",
	HandlerType: (*PoolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPool",
			Handler:    _PoolService_ListPool_Handler,
		},
		{
			MethodName: "SetPool",
			Handler:    _PoolService_SetPool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server_v1/pool.proto",
}
