// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: server_v1/project.proto

package server_v1

import (
	common "github.com/rendau/loom/api/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProjectMain struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image       string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	ImageDigest string                 `protobuf:"bytes,3,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	// Авто-обновление: poll-синк digest'а тега образа.
	AutoUpdate bool                   `protobuf:"varint,4,opt,name=auto_update,json=autoUpdate,proto3" json:"auto_update,omitempty"`
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ModifiedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=modified_at,json=modifiedAt,proto3,oneof" json:"modified_at,omitempty"`
	// Даги образа (каталог `describe`); заполняется в GetProject.
	Templates []*ProjectTemplateMain `protobuf:"bytes,7,rep,name=templates,proto3" json:"templates,omitempty"`
	// Сколько дагов-инстансов заведено в проекте.
	DagCount int32 `protobuf:"varint,8,opt,name=dag_count,json=dagCount,proto3" json:"dag_count,omitempty"`
	// Размер образа в registry (config + слои, сжатыми) — сколько тянет
	// pull; 0 — registry не удалось опросить при регистрации.
	ImageSizeBytes int64 `protobuf:"varint,9,opt,name=image_size_bytes,json=imageSizeBytes,proto3" json:"image_size_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProjectMain) Reset() {
	*x = ProjectMain{}
	mi := &file_server_v1_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMain) ProtoMessage() {}

func (x *ProjectMain) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMain.ProtoReflect.Descriptor instead.
func (*ProjectMain) Descriptor() ([]byte, []int) {
	return file_server_v1_project_proto_rawDescGZIP(), []int{0}
}

func (x *ProjectMain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectMain) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ProjectMain) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

func (x *ProjectMain) GetAutoUpdate() bool {
	if x != nil {
		return x.AutoUpdate
	}
	return false
}

func (x *ProjectMain) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProjectMain) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

func (x *ProjectMain) GetTemplates() []*ProjectTemplateMain {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *ProjectMain) GetDagCount() int32 {
	if x != nil {
		return x.DagCount
	}
	return 0
}

func (x *ProjectMain) GetImageSizeBytes() int64 {
	if x != nil {
		return x.ImageSizeBytes
	}
	return 0
}

// ProjectTemplateMain — даг, объявленный в образе. От него заводят
// инстансы; манифест хранится один раз здесь.
type ProjectTemplateMain struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Name       string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SdkVersion string                 `protobuf:"bytes,2,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	// Шаблон пропал из образа при последней регистрации: его инстансы
	// работают на последнем известном манифесте.
	Orphaned bool `protobuf:"varint,3,opt,name=orphaned,proto3" json:"orphaned,omitempty"`
	// Лимит одновременно выполняющихся ранов; 0 — без лимита.
	MaxActiveRuns int32          `protobuf:"varint,4,opt,name=max_active_runs,json=maxActiveRuns,proto3" json:"max_active_runs,omitempty"`
	Tasks         []*DagTaskMain `protobuf:"bytes,5,rep,name=tasks,proto3" json:"tasks,omitempty"`
	// Сколько дагов-инстансов заведено от этого шаблона.
	DagCount      int32                  `protobuf:"varint,6,opt,name=dag_count,json=dagCount,proto3" json:"dag_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ModifiedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=modified_at,json=modifiedAt,proto3,oneof" json:"modified_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectTemplateMain) Reset() {
	*x = ProjectTemplateMain{}
	mi := &file_server_v1_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectTemplateMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectTemplateMain) ProtoMessage() {}

func (x *ProjectTemplateMain) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectTemplateMain.ProtoReflect.Descriptor instead.
func (*ProjectTemplateMain) Descriptor() ([]byte, []int) {
	return file_server_v1_project_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectTemplateMain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectTemplateMain) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *ProjectTemplateMain) GetOrphaned() bool {
	if x != nil {
		return x.Orphaned
	}
	return false
}

func (x *ProjectTemplateMain) GetMaxActiveRuns() int32 {
	if x != nil {
		return x.MaxActiveRuns
	}
	return 0
}

func (x *ProjectTemplateMain) GetTasks() []*DagTaskMain {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ProjectTemplateMain) GetDagCount() int32 {
	if x != nil {
		return x.DagCount
	}
	return 0
}

func (x *ProjectTemplateMain) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProjectTemplateMain) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

type ProjectRegisterReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Имя проекта: задаётся при регистрации, дальше не меняется.
	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image string `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	// Авто-обновление; отсутствует — сохранить текущее значение
	// (перерегистрация не сбрасывает флаг), у нового проекта — false.
	AutoUpdate *bool `protobuf:"varint,3,opt,name=auto_update,json=autoUpdate,proto3,oneof" json:"auto_update,omitempty"`
	// Заводить даги-инстансы по новым шаблонам образа (по умолчанию true):
	// имя инстанса совпадает с именем дага в образе.
	CreateDags    *bool `protobuf:"varint,4,opt,name=create_dags,json=createDags,proto3,oneof" json:"create_dags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectRegisterReq) Reset() {
	*x = ProjectRegisterReq{}
	mi := &file_server_v1_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectRegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectRegisterReq) ProtoMessage() {}

func (x *ProjectRegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectRegisterReq.ProtoReflect.Descriptor instead.
func (*ProjectRegisterReq) Descriptor() ([]byte, []int) {
	return file_server_v1_project_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectRegisterReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectRegisterReq) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ProjectRegisterReq) GetAutoUpdate() bool {
	if x != nil && x.AutoUpdate != nil {
		return *x.AutoUpdate
	}
	return false
}

func (x *ProjectRegisterReq) GetCreateDags() bool {
	if x != nil && x.CreateDags != nil {
		return *x.CreateDags
	}
	return false
}

type ProjectRegisterRep struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id записи очереди регистраций — для поллинга статуса.
	RegistrationId string `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProjectRegisterRep) Reset() {
	*x = ProjectRegisterRep{}
	mi := &file_server_v1_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectRegisterRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectRegisterRep) ProtoMessage() {}

func (x *ProjectRegisterRep) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectRegisterRep.ProtoReflect.Descriptor instead.
func (*ProjectRegisterRep) Descriptor() ([]byte, []int) {
	return file_server_v1_project_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectRegisterRep) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

type ProjectRegistrationMain struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ProjectName string                 `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	Image       string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Source      string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"` // manual | auto (авто-обновление по digest)
	Status      string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"` // pending | running | success | failed
	Error       string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`   // причина failed
	AutoUpdate  *bool                  `protobuf:"varint,7,opt,name=auto_update,json=autoUpdate,proto3,oneof" json:"auto_update,omitempty"`
	CreateDags  bool                   `protobuf:"varint,8,opt,name=create_dags,json=createDags,proto3" json:"create_dags,omitempty"`
	// Итог по дагам образа: у каждого либо ошибка манифеста, либо признак
	// заведённого инстанса.
	Result        []*ProjectRegistrationDag `protobuf:"bytes,9,rep,name=result,proto3" json:"result,omitempty"`
	CreatedAt     *timestamppb.Timestamp    `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt     *timestamppb.Timestamp    `protobuf:"bytes,11,opt,name=started_at,json=startedAt,proto3,oneof" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp    `protobuf:"bytes,12,opt,name=finished_at,json=finishedAt,proto3,oneof" json:"finished_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectRegistrationMain) Reset() {
	*x = ProjectRegistrationMain{}
	mi := &file_server_v1_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectRegistrationMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectRegistrationMain) ProtoMessage() {}

func (x *ProjectRegistrationMain) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectRegistrationMain.ProtoReflect.Descriptor instead.
func (*ProjectRegistrationMain) Descriptor() ([]byte, []int) {
	return file_server_v1_project_proto_rawDescGZIP(), []int{4}
}

func (x *ProjectRegistrationMain) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProjectRegistrationMain) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *ProjectRegistrationMain) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ProjectRegistrationMain) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ProjectRegistrationMain) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProjectRegistrationMain) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ProjectRegistrationMain) GetAutoUpdate() bool {
	if x != nil && x.AutoUpdate != nil {
		return *x.AutoUpdate
	}
	return false
}

func (x *ProjectRegistrationMain) GetCreateDags() bool {
	if x != nil {
		return x.CreateDags
	}
	return false
}

func (x *ProjectRegistrationMain) GetResult() []*ProjectRegistrationDag {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ProjectRegistrationMain) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProjectRegistrationMain) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ProjectRegistrationMain) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

type ProjectRegistrationDag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`      // пусто — шаблон зарегистрирован
	Created       bool                   `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"` // заведён новый даг-инстанс
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectRegistrationDag) Reset() {
	*x = ProjectRegistrationDag{}
	mi := &file_server_v1_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectRegistrationDag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectRegistrationDag) ProtoMessage() {}

func (x *ProjectRegistrationDag) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectRegistrationDag.ProtoReflect.Descriptor instead.
func (*ProjectRegistrationDag) Descriptor() ([]byte, []int) {
	return file_server_v1_project_proto_rawDescGZIP(), []int{5}
}

func (x *ProjectRegistrationDag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectRegistrationDag) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ProjectRegistrationDag) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type ProjectRegistrationListReq struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ProjectName *string                `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3,oneof" json:"project_name,omitempty"`
	// true — только незавершённые (pending | running).
	Active        *bool `protobuf:"varint,2,opt,name=active,proto3,oneof" json:"active,omitempty"`
	Limit         int64 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"` // 0 — дефолт сервера (50)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectRegistrationListReq) Reset() {
	*x = ProjectRegistrationListReq{}
	mi := &file_server_v1_project_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectRegistrationListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectRegistrationListReq) ProtoMessage() {}

func (x *ProjectRegistrationListReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_project_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectRegistrationListReq.ProtoReflect.Descriptor instead.
func (*ProjectRegistrationListReq) Descriptor() ([]byte, []int) {
	return file_server_v1_project_proto_rawDescGZIP(), []int{6}
}

func (x *ProjectRegistrationListReq) GetProjectName() string {
	if x != nil && x.ProjectName != nil {
		return *x.ProjectName
	}
	return ""
}

func (x *ProjectRegistrationListReq) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}

func (x *ProjectRegistrationListReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ProjectRegistrationListRep struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Results       []*ProjectRegistrationMain `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectRegistrationListRep) Reset() {
	*x = ProjectRegistrationListRep{}
	mi := &file_server_v1_project_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectRegistrationListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectRegistrationListRep) ProtoMessage() {}

func (x *ProjectRegistrationListRep) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_project_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectRegistrationListRep.ProtoReflect.Descriptor instead.
func (*ProjectRegistrationListRep) Descriptor() ([]byte, []int) {
	return file_server_v1_project_proto_rawDescGZIP(), []int{7}
}

func (x *ProjectRegistrationListRep) GetResults() []*ProjectRegistrationMain {
	if x != nil {
		return x.Results
	}
	return nil
}

type ProjectRegistrationGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectRegistrationGetReq) Reset() {
	*x = ProjectRegistrationGetReq{}
	mi := &file_server_v1_project_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectRegistrationGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectRegistrationGetReq) ProtoMessage() {}

func (x *ProjectRegistrationGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_project_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectRegistrationGetReq.ProtoReflect.Descriptor instead.
func (*ProjectRegistrationGetReq) Descriptor() ([]byte, []int) {
	return file_server_v1_project_proto_rawDescGZIP(), []int{8}
}

func (x *ProjectRegistrationGetReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ProjectListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListParams    *common.ListParamsSt   `protobuf:"bytes,1,opt,name=list_params,json=listParams,proto3" json:"list_params,omitempty"`
	AutoUpdate    *bool                  `protobuf:"varint,2,opt,name=auto_update,json=autoUpdate,proto3,oneof" json:"auto_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectListReq) Reset() {
	*x = ProjectListReq{}
	mi := &file_server_v1_project_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectListReq) ProtoMessage() {}

func (x *ProjectListReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_project_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectListReq.ProtoReflect.Descriptor instead.
func (*ProjectListReq) Descriptor() ([]byte, []int) {
	return file_server_v1_project_proto_rawDescGZIP(), []int{9}
}

func (x *ProjectListReq) GetListParams() *common.ListParamsSt {
	if x != nil {
		return x.ListParams
	}
	return nil
}

func (x *ProjectListReq) GetAutoUpdate() bool {
	if x != nil && x.AutoUpdate != nil {
		return *x.AutoUpdate
	}
	return false
}

type ProjectListRep struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	PaginationInfo *common.PaginationInfoSt `protobuf:"bytes,1,opt,name=pagination_info,json=paginationInfo,proto3" json:"pagination_info,omitempty"`
	Results        []*ProjectMain           `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProjectListRep) Reset() {
	*x = ProjectListRep{}
	mi := &file_server_v1_project_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectListRep) ProtoMessage() {}

func (x *ProjectListRep) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_project_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectListRep.ProtoReflect.Descriptor instead.
func (*ProjectListRep) Descriptor() ([]byte, []int) {
	return file_server_v1_project_proto_rawDescGZIP(), []int{10}
}

func (x *ProjectListRep) GetPaginationInfo() *common.PaginationInfoSt {
	if x != nil {
		return x.PaginationInfo
	}
	return nil
}

func (x *ProjectListRep) GetResults() []*ProjectMain {
	if x != nil {
		return x.Results
	}
	return nil
}

type ProjectGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectGetReq) Reset() {
	*x = ProjectGetReq{}
	mi := &file_server_v1_project_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectGetReq) ProtoMessage() {}

func (x *ProjectGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_project_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectGetReq.ProtoReflect.Descriptor instead.
func (*ProjectGetReq) Descriptor() ([]byte, []int) {
	return file_server_v1_project_proto_rawDescGZIP(), []int{11}
}

func (x *ProjectGetReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProjectSyncReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectSyncReq) Reset() {
	*x = ProjectSyncReq{}
	mi := &file_server_v1_project_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectSyncReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectSyncReq) ProtoMessage() {}

func (x *ProjectSyncReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_project_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectSyncReq.ProtoReflect.Descriptor instead.
func (*ProjectSyncReq) Descriptor() ([]byte, []int) {
	return file_server_v1_project_proto_rawDescGZIP(), []int{12}
}

func (x *ProjectSyncReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProjectSyncRep struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RegistrationId string                 `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProjectSyncRep) Reset() {
	*x = ProjectSyncRep{}
	mi := &file_server_v1_project_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectSyncRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectSyncRep) ProtoMessage() {}

func (x *ProjectSyncRep) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_project_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectSyncRep.ProtoReflect.Descriptor instead.
func (*ProjectSyncRep) Descriptor() ([]byte, []int) {
	return file_server_v1_project_proto_rawDescGZIP(), []int{13}
}

func (x *ProjectSyncRep) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

type ProjectSetAutoUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AutoUpdate    bool                   `protobuf:"varint,2,opt,name=auto_update,json=autoUpdate,proto3" json:"auto_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectSetAutoUpdateReq) Reset() {
	*x = ProjectSetAutoUpdateReq{}
	mi := &file_server_v1_project_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectSetAutoUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectSetAutoUpdateReq) ProtoMessage() {}

func (x *ProjectSetAutoUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_project_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectSetAutoUpdateReq.ProtoReflect.Descriptor instead.
func (*ProjectSetAutoUpdateReq) Descriptor() ([]byte, []int) {
	return file_server_v1_project_proto_rawDescGZIP(), []int{14}
}

func (x *ProjectSetAutoUpdateReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectSetAutoUpdateReq) GetAutoUpdate() bool {
	if x != nil {
		return x.AutoUpdate
	}
	return false
}

type ProjectDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectDeleteReq) Reset() {
	*x = ProjectDeleteReq{}
	mi := &file_server_v1_project_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectDeleteReq) ProtoMessage() {}

func (x *ProjectDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_project_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectDeleteReq.ProtoReflect.Descriptor instead.
func (*ProjectDeleteReq) Descriptor() ([]byte, []int) {
	return file_server_v1_project_proto_rawDescGZIP(), []int{15}
}

func (x *ProjectDeleteReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DagPushCatalogReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DescribeId    string                 `protobuf:"bytes,1,opt,name=describe_id,json=describeId,proto3" json:"describe_id,omitempty"`
	Catalog       []byte                 `protobuf:"bytes,2,opt,name=catalog,proto3" json:"catalog,omitempty"` // JSON-каталог образа (вывод `describe`)
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`     // непустая — describe упал целиком
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DagPushCatalogReq) Reset() {
	*x = DagPushCatalogReq{}
	mi := &file_server_v1_project_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DagPushCatalogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DagPushCatalogReq) ProtoMessage() {}

func (x *DagPushCatalogReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_project_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DagPushCatalogReq.ProtoReflect.Descriptor instead.
func (*DagPushCatalogReq) Descriptor() ([]byte, []int) {
	return file_server_v1_project_proto_rawDescGZIP(), []int{16}
}

func (x *DagPushCatalogReq) GetDescribeId() string {
	if x != nil {
		return x.DescribeId
	}
	return ""
}

func (x *DagPushCatalogReq) GetCatalog() []byte {
	if x != nil {
		return x.Catalog
	}
	return nil
}

func (x *DagPushCatalogReq) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_server_v1_project_proto protoreflect.FileDescriptor

const file_server_v1_project_proto_rawDesc = "" +
	"\n" +
	"\x17server_v1/project.proto\x12\tserver_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\x1a\x13server_v1/dag.proto\"\x8d\x03\n" +
	"\vProjectMain\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12!\n" +
	"\fimage_digest\x18\x03 \x01(\tR\vimageDigest\x12\x1f\n" +
	"\vauto_update\x18\x04 \x01(\bR\n" +
	"autoUpdate\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12@\n" +
	"\vmodified_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"modifiedAt\x88\x01\x01\x12<\n" +
	"\ttemplates\x18\a \x03(\v2\x1e.server_v1.ProjectTemplateMainR\ttemplates\x12\x1b\n" +
	"\tdag_count\x18\b \x01(\x05R\bdagCount\x12(\n" +
	"\x10image_size_bytes\x18\t \x01(\x03R\x0eimageSizeBytesB\x0e\n" +
	"\f_modified_at\"\xe6\x02\n" +
	"\x13ProjectTemplateMain\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vsdk_version\x18\x02 \x01(\tR\n" +
	"sdkVersion\x12\x1a\n" +
	"\borphaned\x18\x03 \x01(\bR\borphaned\x12&\n" +
	"\x0fmax_active_runs\x18\x04 \x01(\x05R\rmaxActiveRuns\x12,\n" +
	"\x05tasks\x18\x05 \x03(\v2\x16.server_v1.DagTaskMainR\x05tasks\x12\x1b\n" +
	"\tdag_count\x18\x06 \x01(\x05R\bdagCount\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12@\n" +
	"\vmodified_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"modifiedAt\x88\x01\x01B\x0e\n" +
	"\f_modified_at\"\xaa\x01\n" +
	"\x12ProjectRegisterReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12$\n" +
	"\vauto_update\x18\x03 \x01(\bH\x00R\n" +
	"autoUpdate\x88\x01\x01\x12$\n" +
	"\vcreate_dags\x18\x04 \x01(\bH\x01R\n" +
	"createDags\x88\x01\x01B\x0e\n" +
	"\f_auto_updateB\x0e\n" +
	"\f_create_dags\"=\n" +
	"\x12ProjectRegisterRep\x12'\n" +
	"\x0fregistration_id\x18\x01 \x01(\tR\x0eregistrationId\"\x96\x04\n" +
	"\x17ProjectRegistrationMain\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fproject_name\x18\x02 \x01(\tR\vprojectName\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12$\n" +
	"\vauto_update\x18\a \x01(\bH\x00R\n" +
	"autoUpdate\x88\x01\x01\x12\x1f\n" +
	"\vcreate_dags\x18\b \x01(\bR\n" +
	"createDags\x129\n" +
	"\x06result\x18\t \x03(\v2!.server_v1.ProjectRegistrationDagR\x06result\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12>\n" +
	"\n" +
	"started_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampH\x01R\tstartedAt\x88\x01\x01\x12@\n" +
	"\vfinished_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampH\x02R\n" +
	"finishedAt\x88\x01\x01B\x0e\n" +
	"\f_auto_updateB\r\n" +
	"\v_started_atB\x0e\n" +
	"\f_finished_at\"\\\n" +
	"\x16ProjectRegistrationDag\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\acreated\x18\x03 \x01(\bR\acreated\"\x93\x01\n" +
	"\x1aProjectRegistrationListReq\x12&\n" +
	"\fproject_name\x18\x01 \x01(\tH\x00R\vprojectName\x88\x01\x01\x12\x1b\n" +
	"\x06active\x18\x02 \x01(\bH\x01R\x06active\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limitB\x0f\n" +
	"\r_project_nameB\t\n" +
	"\a_active\"Z\n" +
	"\x1aProjectRegistrationListRep\x12<\n" +
	"\aresults\x18\x01 \x03(\v2\".server_v1.ProjectRegistrationMainR\aresults\"+\n" +
	"\x19ProjectRegistrationGetReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"}\n" +
	"\x0eProjectListReq\x125\n" +
	"\vlist_params\x18\x01 \x01(\v2\x14.common.ListParamsStR\n" +
	"listParams\x12$\n" +
	"\vauto_update\x18\x02 \x01(\bH\x00R\n" +
	"autoUpdate\x88\x01\x01B\x0e\n" +
	"\f_auto_update\"\x85\x01\n" +
	"\x0eProjectListRep\x12A\n" +
	"\x0fpagination_info\x18\x01 \x01(\v2\x18.common.PaginationInfoStR\x0epaginationInfo\x120\n" +
	"\aresults\x18\x02 \x03(\v2\x16.server_v1.ProjectMainR\aresults\"#\n" +
	"\rProjectGetReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"$\n" +
	"\x0eProjectSyncReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"9\n" +
	"\x0eProjectSyncRep\x12'\n" +
	"\x0fregistration_id\x18\x01 \x01(\tR\x0eregistrationId\"N\n" +
	"\x17ProjectSetAutoUpdateReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vauto_update\x18\x02 \x01(\bR\n" +
	"autoUpdate\"&\n" +
	"\x10ProjectDeleteReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"d\n" +
	"\x11DagPushCatalogReq\x12\x1f\n" +
	"\vdescribe_id\x18\x01 \x01(\tR\n" +
	"describeId\x12\x18\n" +
	"\acatalog\x18\x02 \x01(\fR\acatalog\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\xde\a\n" +
	"\x0eProjectService\x12d\n" +
	"\x0fRegisterProject\x12\x1d.server_v1.ProjectRegisterReq\x1a\x1d.server_v1.ProjectRegisterRep\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/project\x12U\n" +
	"\vListProject\x12\x19.server_v1.ProjectListReq\x1a\x19.server_v1.ProjectListRep\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/project\x12W\n" +
	"\n" +
	"GetProject\x12\x18.server_v1.ProjectGetReq\x1a\x16.server_v1.ProjectMain\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/project/{name}\x12d\n" +
	"\vSyncProject\x12\x19.server_v1.ProjectSyncReq\x1a\x19.server_v1.ProjectSyncRep\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/project/{name}/sync\x12z\n" +
	"\x14SetProjectAutoUpdate\x12\".server_v1.ProjectSetAutoUpdateReq\x1a\x16.google.protobuf.Empty\"&\x82\xd3\xe4\x93\x02 :\x01*\x1a\x1b/project/{name}/auto_update\x12]\n" +
	"\rDeleteProject\x12\x1b.server_v1.ProjectDeleteReq\x1a\x16.google.protobuf.Empty\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/project/{name}\x12\x86\x01\n" +
	"\x17ListProjectRegistration\x12%.server_v1.ProjectRegistrationListReq\x1a%.server_v1.ProjectRegistrationListRep\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/project-registration\x12\x86\x01\n" +
	"\x16GetProjectRegistration\x12$.server_v1.ProjectRegistrationGetReq\x1a\".server_v1.ProjectRegistrationMain\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/project-registration/{id}\x12c\n" +
	"\x0ePushDagCatalog\x12\x1c.server_v1.DagPushCatalogReq\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/project/catalogB0Z.github.com/rendau/loom/api/server_v1;server_v1b\x06proto3"

var (
	file_server_v1_project_proto_rawDescOnce sync.Once
	file_server_v1_project_proto_rawDescData []byte
)

func file_server_v1_project_proto_rawDescGZIP() []byte {
	file_server_v1_project_proto_rawDescOnce.Do(func() {
		file_server_v1_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_v1_project_proto_rawDesc), len(file_server_v1_project_proto_rawDesc)))
	})
	return file_server_v1_project_proto_rawDescData
}

var file_server_v1_project_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_server_v1_project_proto_goTypes = []any{
	(*ProjectMain)(nil),                // 0: server_v1.ProjectMain
	(*ProjectTemplateMain)(nil),        // 1: server_v1.ProjectTemplateMain
	(*ProjectRegisterReq)(nil),         // 2: server_v1.ProjectRegisterReq
	(*ProjectRegisterRep)(nil),         // 3: server_v1.ProjectRegisterRep
	(*ProjectRegistrationMain)(nil),    // 4: server_v1.ProjectRegistrationMain
	(*ProjectRegistrationDag)(nil),     // 5: server_v1.ProjectRegistrationDag
	(*ProjectRegistrationListReq)(nil), // 6: server_v1.ProjectRegistrationListReq
	(*ProjectRegistrationListRep)(nil), // 7: server_v1.ProjectRegistrationListRep
	(*ProjectRegistrationGetReq)(nil),  // 8: server_v1.ProjectRegistrationGetReq
	(*ProjectListReq)(nil),             // 9: server_v1.ProjectListReq
	(*ProjectListRep)(nil),             // 10: server_v1.ProjectListRep
	(*ProjectGetReq)(nil),              // 11: server_v1.ProjectGetReq
	(*ProjectSyncReq)(nil),             // 12: server_v1.ProjectSyncReq
	(*ProjectSyncRep)(nil),             // 13: server_v1.ProjectSyncRep
	(*ProjectSetAutoUpdateReq)(nil),    // 14: server_v1.ProjectSetAutoUpdateReq
	(*ProjectDeleteReq)(nil),           // 15: server_v1.ProjectDeleteReq
	(*DagPushCatalogReq)(nil),          // 16: server_v1.DagPushCatalogReq
	(*timestamppb.Timestamp)(nil),      // 17: google.protobuf.Timestamp
	(*DagTaskMain)(nil),                // 18: server_v1.DagTaskMain
	(*common.ListParamsSt)(nil),        // 19: common.ListParamsSt
	(*common.PaginationInfoSt)(nil),    // 20: common.PaginationInfoSt
	(*emptypb.Empty)(nil),              // 21: google.protobuf.Empty
}
var file_server_v1_project_proto_depIdxs = []int32{
	17, // 0: server_v1.ProjectMain.created_at:type_name -> google.protobuf.Timestamp
	17, // 1: server_v1.ProjectMain.modified_at:type_name -> google.protobuf.Timestamp
	1,  // 2: server_v1.ProjectMain.templates:type_name -> server_v1.ProjectTemplateMain
	18, // 3: server_v1.ProjectTemplateMain.tasks:type_name -> server_v1.DagTaskMain
	17, // 4: server_v1.ProjectTemplateMain.created_at:type_name -> google.protobuf.Timestamp
	17, // 5: server_v1.ProjectTemplateMain.modified_at:type_name -> google.protobuf.Timestamp
	5,  // 6: server_v1.ProjectRegistrationMain.result:type_name -> server_v1.ProjectRegistrationDag
	17, // 7: server_v1.ProjectRegistrationMain.created_at:type_name -> google.protobuf.Timestamp
	17, // 8: server_v1.ProjectRegistrationMain.started_at:type_name -> google.protobuf.Timestamp
	17, // 9: server_v1.ProjectRegistrationMain.finished_at:type_name -> google.protobuf.Timestamp
	4,  // 10: server_v1.ProjectRegistrationListRep.results:type_name -> server_v1.ProjectRegistrationMain
	19, // 11: server_v1.ProjectListReq.list_params:type_name -> common.ListParamsSt
	20, // 12: server_v1.ProjectListRep.pagination_info:type_name -> common.PaginationInfoSt
	0,  // 13: server_v1.ProjectListRep.results:type_name -> server_v1.ProjectMain
	2,  // 14: server_v1.ProjectService.RegisterProject:input_type -> server_v1.ProjectRegisterReq
	9,  // 15: server_v1.ProjectService.ListProject:input_type -> server_v1.ProjectListReq
	11, // 16: server_v1.ProjectService.GetProject:input_type -> server_v1.ProjectGetReq
	12, // 17: server_v1.ProjectService.SyncProject:input_type -> server_v1.ProjectSyncReq
	14, // 18: server_v1.ProjectService.SetProjectAutoUpdate:input_type -> server_v1.ProjectSetAutoUpdateReq
	15, // 19: server_v1.ProjectService.DeleteProject:input_type -> server_v1.ProjectDeleteReq
	6,  // 20: server_v1.ProjectService.ListProjectRegistration:input_type -> server_v1.ProjectRegistrationListReq
	8,  // 21: server_v1.ProjectService.GetProjectRegistration:input_type -> server_v1.ProjectRegistrationGetReq
	16, // 22: server_v1.ProjectService.PushDagCatalog:input_type -> server_v1.DagPushCatalogReq
	3,  // 23: server_v1.ProjectService.RegisterProject:output_type -> server_v1.ProjectRegisterRep
	10, // 24: server_v1.ProjectService.ListProject:output_type -> server_v1.ProjectListRep
	0,  // 25: server_v1.ProjectService.GetProject:output_type -> server_v1.ProjectMain
	13, // 26: server_v1.ProjectService.SyncProject:output_type -> server_v1.ProjectSyncRep
	21, // 27: server_v1.ProjectService.SetProjectAutoUpdate:output_type -> google.protobuf.Empty
	21, // 28: server_v1.ProjectService.DeleteProject:output_type -> google.protobuf.Empty
	7,  // 29: server_v1.ProjectService.ListProjectRegistration:output_type -> server_v1.ProjectRegistrationListRep
	4,  // 30: server_v1.ProjectService.GetProjectRegistration:output_type -> server_v1.ProjectRegistrationMain
	21, // 31: server_v1.ProjectService.PushDagCatalog:output_type -> google.protobuf.Empty
	23, // [23:32] is the sub-list for method output_type
	14, // [14:23] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_server_v1_project_proto_init() }
func file_server_v1_project_proto_init() {
	if File_server_v1_project_proto != nil {
		return
	}
	file_server_v1_dag_proto_init()
	file_server_v1_project_proto_msgTypes[0].OneofWrappers = []any{}
	file_server_v1_project_proto_msgTypes[1].OneofWrappers = []any{}
	file_server_v1_project_proto_msgTypes[2].OneofWrappers = []any{}
	file_server_v1_project_proto_msgTypes[4].OneofWrappers = []any{}
	file_server_v1_project_proto_msgTypes[6].OneofWrappers = []any{}
	file_server_v1_project_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_v1_project_proto_rawDesc), len(file_server_v1_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_v1_project_proto_goTypes,
		DependencyIndexes: file_server_v1_project_proto_depIdxs,
		MessageInfos:      file_server_v1_project_proto_msgTypes,
	}.Build()
	File_server_v1_project_proto = out.File
	file_server_v1_project_proto_goTypes = nil
	file_server_v1_project_proto_depIdxs = nil
}
