// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: server_v1/project.proto

package server_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProjectService_RegisterProject_FullMethodName         = "/server_v1.ProjectService/RegisterProject"
	ProjectService_ListProject_FullMethodName             = "/server_v1.ProjectService/ListProject"
	ProjectService_GetProject_FullMethodName              = "/server_v1.ProjectService/GetProject"
	ProjectService_SyncProject_FullMethodName             = "/server_v1.ProjectService/SyncProject"
	ProjectService_SetProjectAutoUpdate_FullMethodName    = "/server_v1.ProjectService/SetProjectAutoUpdate"
	ProjectService_DeleteProject_FullMethodName           = "/server_v1.ProjectService/DeleteProject"
	ProjectService_ListProjectRegistration_FullMethodName = "/server_v1.ProjectService/ListProjectRegistration"
	ProjectService_GetProjectRegistration_FullMethodName  = "/server_v1.ProjectService/GetProjectRegistration"
	ProjectService_PushDagCatalog_FullMethodName          = "/server_v1.ProjectService/PushDagCatalog"
)

// ProjectServiceClient is the client API for ProjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProjectService — проекты: docker-образ и объявленные в нём даги.
//
// Один образ может нести несколько дагов: server запускает контейнер в
// режиме `describe`, получает каталог образа и сохраняет его даги как
// шаблоны проекта, пиннуя образ к digest на момент регистрации. От
// шаблона заводят даги-инстансы (DagService.CreateDag) — сколько угодно,
// у каждого свои расписание, пул, переменные и секреты.
type ProjectServiceClient interface {
	// RegisterProject ставит регистрацию (или перерегистрацию — новая версия
	// образа) проекта в очередь и сразу возвращает id записи регистрации:
	// pull + describe выполняются асинхронно, статус — через
	// Get/ListProjectRegistration.
	RegisterProject(ctx context.Context, in *ProjectRegisterReq, opts ...grpc.CallOption) (*ProjectRegisterRep, error)
	ListProject(ctx context.Context, in *ProjectListReq, opts ...grpc.CallOption) (*ProjectListRep, error)
	// GetProject отдаёт проект вместе с каталогом его образа (шаблонами).
	GetProject(ctx context.Context, in *ProjectGetReq, opts ...grpc.CallOption) (*ProjectMain, error)
	// SyncProject — принудительное обновление из registry: перерегистрация
	// текущего образа проекта прямо сейчас, не дожидаясь тика
	// авто-обновления. Кладётся в ту же очередь (source=manual).
	SyncProject(ctx context.Context, in *ProjectSyncReq, opts ...grpc.CallOption) (*ProjectSyncRep, error)
	// SetProjectAutoUpdate включает/выключает авто-обновление образа:
	// control plane периодически сверяет digest тега с registry и при
	// изменении перерегистрирует проект целиком.
	SetProjectAutoUpdate(ctx context.Context, in *ProjectSetAutoUpdateReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// DeleteProject удаляет проект вместе с его шаблонами и дагами.
	DeleteProject(ctx context.Context, in *ProjectDeleteReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListProjectRegistration — записи очереди регистраций, новые первыми:
	// активные (pending|running) и недавно завершённые (старые чистятся по
	// TTL). source=auto — перерегистрация авто-обновления по digest.
	ListProjectRegistration(ctx context.Context, in *ProjectRegistrationListReq, opts ...grpc.CallOption) (*ProjectRegistrationListRep, error)
	GetProjectRegistration(ctx context.Context, in *ProjectRegistrationGetReq, opts ...grpc.CallOption) (*ProjectRegistrationMain, error)
	// PushDagCatalog — внутренний вызов describe-Job'а: при регистрации через
	// kubernetes Job сам отправляет каталог образа (или ошибку) на control
	// plane, вместо передачи через логи пода. describe_id — одноразовый
	// секрет, выданный Job'у в env при создании.
	PushDagCatalog(ctx context.Context, in *DagPushCatalogReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type projectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectServiceClient(cc grpc.ClientConnInterface) ProjectServiceClient {
	return &projectServiceClient{cc}
}

func (c *projectServiceClient) RegisterProject(ctx context.Context, in *ProjectRegisterReq, opts ...grpc.CallOption) (*ProjectRegisterRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectRegisterRep)
	err := c.cc.Invoke(ctx, ProjectService_RegisterProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) ListProject(ctx context.Context, in *ProjectListReq, opts ...grpc.CallOption) (*ProjectListRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectListRep)
	err := c.cc.Invoke(ctx, ProjectService_ListProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetProject(ctx context.Context, in *ProjectGetReq, opts ...grpc.CallOption) (*ProjectMain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectMain)
	err := c.cc.Invoke(ctx, ProjectService_GetProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) SyncProject(ctx context.Context, in *ProjectSyncReq, opts ...grpc.CallOption) (*ProjectSyncRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectSyncRep)
	err := c.cc.Invoke(ctx, ProjectService_SyncProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) SetProjectAutoUpdate(ctx context.Context, in *ProjectSetAutoUpdateReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ProjectService_SetProjectAutoUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) DeleteProject(ctx context.Context, in *ProjectDeleteReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ProjectService_DeleteProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) ListProjectRegistration(ctx context.Context, in *ProjectRegistrationListReq, opts ...grpc.CallOption) (*ProjectRegistrationListRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectRegistrationListRep)
	err := c.cc.Invoke(ctx, ProjectService_ListProjectRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) GetProjectRegistration(ctx context.Context, in *ProjectRegistrationGetReq, opts ...grpc.CallOption) (*ProjectRegistrationMain, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectRegistrationMain)
	err := c.cc.Invoke(ctx, ProjectService_GetProjectRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) PushDagCatalog(ctx context.Context, in *DagPushCatalogReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ProjectService_PushDagCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectServiceServer is the server API for ProjectService service.
// All implementations must embed UnimplementedProjectServiceServer
// for forward compatibility.
//
// ProjectService — проекты: docker-образ и объявленные в нём даги.
//
// Один образ может нести несколько дагов: server запускает контейнер в
// режиме `describe`, получает каталог образа и сохраняет его даги как
// шаблоны проекта, пиннуя образ к digest на момент регистрации. От
// шаблона заводят даги-инстансы (DagService.CreateDag) — сколько угодно,
// у каждого свои расписание, пул, переменные и секреты.
type ProjectServiceServer interface {
	// RegisterProject ставит регистрацию (или перерегистрацию — новая версия
	// образа) проекта в очередь и сразу возвращает id записи регистрации:
	// pull + describe выполняются асинхронно, статус — через
	// Get/ListProjectRegistration.
	RegisterProject(context.Context, *ProjectRegisterReq) (*ProjectRegisterRep, error)
	ListProject(context.Context, *ProjectListReq) (*ProjectListRep, error)
	// GetProject отдаёт проект вместе с каталогом его образа (шаблонами).
	GetProject(context.Context, *ProjectGetReq) (*ProjectMain, error)
	// SyncProject — принудительное обновление из registry: перерегистрация
	// текущего образа проекта прямо сейчас, не дожидаясь тика
	// авто-обновления. Кладётся в ту же очередь (source=manual).
	SyncProject(context.Context, *ProjectSyncReq) (*ProjectSyncRep, error)
	// SetProjectAutoUpdate включает/выключает авто-обновление образа:
	// control plane периодически сверяет digest тега с registry и при
	// изменении перерегистрирует проект целиком.
	SetProjectAutoUpdate(context.Context, *ProjectSetAutoUpdateReq) (*emptypb.Empty, error)
	// DeleteProject удаляет проект вместе с его шаблонами и дагами.
	DeleteProject(context.Context, *ProjectDeleteReq) (*emptypb.Empty, error)
	// ListProjectRegistration — записи очереди регистраций, новые первыми:
	// активные (pending|running) и недавно завершённые (старые чистятся по
	// TTL). source=auto — перерегистрация авто-обновления по digest.
	ListProjectRegistration(context.Context, *ProjectRegistrationListReq) (*ProjectRegistrationListRep, error)
	GetProjectRegistration(context.Context, *ProjectRegistrationGetReq) (*ProjectRegistrationMain, error)
	// PushDagCatalog — внутренний вызов describe-Job'а: при регистрации через
	// kubernetes Job сам отправляет каталог образа (или ошибку) на control
	// plane, вместо передачи через логи пода. describe_id — одноразовый
	// секрет, выданный Job'у в env при создании.
	PushDagCatalog(context.Context, *DagPushCatalogReq) (*emptypb.Empty, error)
	mustEmbedUnimplementedProjectServiceServer()
}

// UnimplementedProjectServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProjectServiceServer struct{}

func (UnimplementedProjectServiceServer) RegisterProject(context.Context, *ProjectRegisterReq) (*ProjectRegisterRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterProject not implemented")
}
func (UnimplementedProjectServiceServer) ListProject(context.Context, *ProjectListReq) (*ProjectListRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProject not implemented")
}
func (UnimplementedProjectServiceServer) GetProject(context.Context, *ProjectGetReq) (*ProjectMain, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProject not implemented")
}
func (UnimplementedProjectServiceServer) SyncProject(context.Context, *ProjectSyncReq) (*ProjectSyncRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncProject not implemented")
}
func (UnimplementedProjectServiceServer) SetProjectAutoUpdate(context.Context, *ProjectSetAutoUpdateReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetProjectAutoUpdate not implemented")
}
func (UnimplementedProjectServiceServer) DeleteProject(context.Context, *ProjectDeleteReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProject not implemented")
}
func (UnimplementedProjectServiceServer) ListProjectRegistration(context.Context, *ProjectRegistrationListReq) (*ProjectRegistrationListRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProjectRegistration not implemented")
}
func (UnimplementedProjectServiceServer) GetProjectRegistration(context.Context, *ProjectRegistrationGetReq) (*ProjectRegistrationMain, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProjectRegistration not implemented")
}
func (UnimplementedProjectServiceServer) PushDagCatalog(context.Context, *DagPushCatalogReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushDagCatalog not implemented")
}
func (UnimplementedProjectServiceServer) mustEmbedUnimplementedProjectServiceServer() {}
func (UnimplementedProjectServiceServer) testEmbeddedByValue()                        {}

// UnsafeProjectServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjectServiceServer will
// result in compilation errors.
type UnsafeProjectServiceServer interface {
	mustEmbedUnimplementedProjectServiceServer()
}

func RegisterProjectServiceServer(s grpc.ServiceRegistrar, srv ProjectServiceServer) {
	// If the following call pancis, it indicates UnimplementedProjectServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProjectService_ServiceDesc, srv)
}

func _ProjectService_RegisterProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).RegisterProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_RegisterProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).RegisterProject(ctx, req.(*ProjectRegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_ListProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).ListProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_ListProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).ListProject(ctx, req.(*ProjectListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetProject(ctx, req.(*ProjectGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_SyncProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectSyncReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).SyncProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_SyncProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).SyncProject(ctx, req.(*ProjectSyncReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_SetProjectAutoUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectSetAutoUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).SetProjectAutoUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_SetProjectAutoUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).SetProjectAutoUpdate(ctx, req.(*ProjectSetAutoUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_DeleteProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).DeleteProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_DeleteProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).DeleteProject(ctx, req.(*ProjectDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_ListProjectRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRegistrationListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).ListProjectRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_ListProjectRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).ListProjectRegistration(ctx, req.(*ProjectRegistrationListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_GetProjectRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectRegistrationGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).GetProjectRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_GetProjectRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).GetProjectRegistration(ctx, req.(*ProjectRegistrationGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_PushDagCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DagPushCatalogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).PushDagCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProjectService_PushDagCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).PushDagCatalog(ctx, req.(*DagPushCatalogReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjectService_ServiceDesc is the grpc.ServiceDesc for ProjectService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjectService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server_v1.ProjectService",
	HandlerType: (*ProjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterProject",
			Handler:    _ProjectService_RegisterProject_Handler,
		},
		{
			MethodName: "ListProject",
			Handler:    _ProjectService_ListProject_Handler,
		},
		{
			MethodName: "GetProject",
			Handler:    _ProjectService_GetProject_Handler,
		},
		{
			MethodName: "SyncProject",
			Handler:    _ProjectService_SyncProject_Handler,
		},
		{
			MethodName: "SetProjectAutoUpdate",
			Handler:    _ProjectService_SetProjectAutoUpdate_Handler,
		},
		{
			MethodName: "DeleteProject",
			Handler:    _ProjectService_DeleteProject_Handler,
		},
		{
			MethodName: "ListProjectRegistration",
			Handler:    _ProjectService_ListProjectRegistration_Handler,
		},
		{
			MethodName: "GetProjectRegistration",
			Handler:    _ProjectService_GetProjectRegistration_Handler,
		},
		{
			MethodName: "PushDagCatalog",
			Handler:    _ProjectService_PushDagCatalog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server_v1/project.proto",
}
