// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: server_v1/run.proto

package server_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RunService_TriggerRun_FullMethodName = "/server_v1.RunService/TriggerRun"
	RunService_ListRun_FullMethodName    = "/server_v1.RunService/ListRun"
	RunService_GetRun_FullMethodName     = "/server_v1.RunService/GetRun"
)

// RunServiceClient is the client API for RunService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RunService — запуски дагов: ручной триггер, журнал ранов, детали рана
// (статусы тасков и попыток).
type RunServiceClient interface {
	// TriggerRun создаёт ран дага: снапшот манифеста и digest образа пиннятся
	// на момент триггера, таски раскручиваются планировщиком.
	TriggerRun(ctx context.Context, in *RunTriggerReq, opts ...grpc.CallOption) (*RunTriggerRep, error)
	ListRun(ctx context.Context, in *RunListReq, opts ...grpc.CallOption) (*RunListRep, error)
	// GetRun возвращает ран вместе с task instance'ами и их попытками.
	GetRun(ctx context.Context, in *RunGetReq, opts ...grpc.CallOption) (*RunGetRep, error)
}

type runServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRunServiceClient(cc grpc.ClientConnInterface) RunServiceClient {
	return &runServiceClient{cc}
}

func (c *runServiceClient) TriggerRun(ctx context.Context, in *RunTriggerReq, opts ...grpc.CallOption) (*RunTriggerRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunTriggerRep)
	err := c.cc.Invoke(ctx, RunService_TriggerRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runServiceClient) ListRun(ctx context.Context, in *RunListReq, opts ...grpc.CallOption) (*RunListRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunListRep)
	err := c.cc.Invoke(ctx, RunService_ListRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runServiceClient) GetRun(ctx context.Context, in *RunGetReq, opts ...grpc.CallOption) (*RunGetRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunGetRep)
	err := c.cc.Invoke(ctx, RunService_GetRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunServiceServer is the server API for RunService service.
// All implementations must embed UnimplementedRunServiceServer
// for forward compatibility.
//
// RunService — запуски дагов: ручной триггер, журнал ранов, детали рана
// (статусы тасков и попыток).
type RunServiceServer interface {
	// TriggerRun создаёт ран дага: снапшот манифеста и digest образа пиннятся
	// на момент триггера, таски раскручиваются планировщиком.
	TriggerRun(context.Context, *RunTriggerReq) (*RunTriggerRep, error)
	ListRun(context.Context, *RunListReq) (*RunListRep, error)
	// GetRun возвращает ран вместе с task instance'ами и их попытками.
	GetRun(context.Context, *RunGetReq) (*RunGetRep, error)
	mustEmbedUnimplementedRunServiceServer()
}

// UnimplementedRunServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunServiceServer struct{}

func (UnimplementedRunServiceServer) TriggerRun(context.Context, *RunTriggerReq) (*RunTriggerRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerRun not implemented")
}
func (UnimplementedRunServiceServer) ListRun(context.Context, *RunListReq) (*RunListRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRun not implemented")
}
func (UnimplementedRunServiceServer) GetRun(context.Context, *RunGetReq) (*RunGetRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRun not implemented")
}
func (UnimplementedRunServiceServer) mustEmbedUnimplementedRunServiceServer() {}
func (UnimplementedRunServiceServer) testEmbeddedByValue()                    {}

// UnsafeRunServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunServiceServer will
// result in compilation errors.
type UnsafeRunServiceServer interface {
	mustEmbedUnimplementedRunServiceServer()
}

func RegisterRunServiceServer(s grpc.ServiceRegistrar, srv RunServiceServer) {
	// If the following call pancis, it indicates UnimplementedRunServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RunService_ServiceDesc, srv)
}

func _RunService_TriggerRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunTriggerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunServiceServer).TriggerRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunService_TriggerRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunServiceServer).TriggerRun(ctx, req.(*RunTriggerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunService_ListRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunServiceServer).ListRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunService_ListRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunServiceServer).ListRun(ctx, req.(*RunListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunService_GetRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunServiceServer).GetRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunService_GetRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunServiceServer).GetRun(ctx, req.(*RunGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RunService_ServiceDesc is the grpc.ServiceDesc for RunService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server_v1.RunService",
	HandlerType: (*RunServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TriggerRun",
			Handler:    _RunService_TriggerRun_Handler,
		},
		{
			MethodName: "ListRun",
			Handler:    _RunService_ListRun_Handler,
		},
		{
			MethodName: "GetRun",
			Handler:    _RunService_GetRun_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server_v1/run.proto",
}
