// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: server_v1/secret.proto

package server_v1

import (
	common "github.com/rendau/loom/api/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecretMetaMain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ModifiedAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=modified_at,json=modifiedAt,proto3,oneof" json:"modified_at,omitempty"`
	Scope         *common.ScopeSt        `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretMetaMain) Reset() {
	*x = SecretMetaMain{}
	mi := &file_server_v1_secret_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretMetaMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretMetaMain) ProtoMessage() {}

func (x *SecretMetaMain) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_secret_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretMetaMain.ProtoReflect.Descriptor instead.
func (*SecretMetaMain) Descriptor() ([]byte, []int) {
	return file_server_v1_secret_proto_rawDescGZIP(), []int{0}
}

func (x *SecretMetaMain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecretMetaMain) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SecretMetaMain) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

func (x *SecretMetaMain) GetScope() *common.ScopeSt {
	if x != nil {
		return x.Scope
	}
	return nil
}

type SecretListReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Отсутствует — все скоупы; иначе — только указанный.
	Scope         *common.ScopeSt `protobuf:"bytes,1,opt,name=scope,proto3,oneof" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretListReq) Reset() {
	*x = SecretListReq{}
	mi := &file_server_v1_secret_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretListReq) ProtoMessage() {}

func (x *SecretListReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_secret_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretListReq.ProtoReflect.Descriptor instead.
func (*SecretListReq) Descriptor() ([]byte, []int) {
	return file_server_v1_secret_proto_rawDescGZIP(), []int{1}
}

func (x *SecretListReq) GetScope() *common.ScopeSt {
	if x != nil {
		return x.Scope
	}
	return nil
}

type SecretListRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SecretMetaMain      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretListRep) Reset() {
	*x = SecretListRep{}
	mi := &file_server_v1_secret_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretListRep) ProtoMessage() {}

func (x *SecretListRep) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_secret_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretListRep.ProtoReflect.Descriptor instead.
func (*SecretListRep) Descriptor() ([]byte, []int) {
	return file_server_v1_secret_proto_rawDescGZIP(), []int{2}
}

func (x *SecretListRep) GetResults() []*SecretMetaMain {
	if x != nil {
		return x.Results
	}
	return nil
}

type SecretSetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Scope         *common.ScopeSt        `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"` // пустой — глобальный скоуп
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretSetReq) Reset() {
	*x = SecretSetReq{}
	mi := &file_server_v1_secret_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretSetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretSetReq) ProtoMessage() {}

func (x *SecretSetReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_secret_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretSetReq.ProtoReflect.Descriptor instead.
func (*SecretSetReq) Descriptor() ([]byte, []int) {
	return file_server_v1_secret_proto_rawDescGZIP(), []int{3}
}

func (x *SecretSetReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecretSetReq) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SecretSetReq) GetScope() *common.ScopeSt {
	if x != nil {
		return x.Scope
	}
	return nil
}

type SecretDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Scope         *common.ScopeSt        `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"` // пустой — глобальный скоуп
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretDeleteReq) Reset() {
	*x = SecretDeleteReq{}
	mi := &file_server_v1_secret_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretDeleteReq) ProtoMessage() {}

func (x *SecretDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_secret_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretDeleteReq.ProtoReflect.Descriptor instead.
func (*SecretDeleteReq) Descriptor() ([]byte, []int) {
	return file_server_v1_secret_proto_rawDescGZIP(), []int{4}
}

func (x *SecretDeleteReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecretDeleteReq) GetScope() *common.ScopeSt {
	if x != nil {
		return x.Scope
	}
	return nil
}

type SecretGetValueReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Scope         *common.ScopeSt        `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"` // пустой — глобальный скоуп
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretGetValueReq) Reset() {
	*x = SecretGetValueReq{}
	mi := &file_server_v1_secret_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretGetValueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretGetValueReq) ProtoMessage() {}

func (x *SecretGetValueReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_secret_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretGetValueReq.ProtoReflect.Descriptor instead.
func (*SecretGetValueReq) Descriptor() ([]byte, []int) {
	return file_server_v1_secret_proto_rawDescGZIP(), []int{5}
}

func (x *SecretGetValueReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecretGetValueReq) GetScope() *common.ScopeSt {
	if x != nil {
		return x.Scope
	}
	return nil
}

type SecretValueRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretValueRep) Reset() {
	*x = SecretValueRep{}
	mi := &file_server_v1_secret_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretValueRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretValueRep) ProtoMessage() {}

func (x *SecretValueRep) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_secret_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretValueRep.ProtoReflect.Descriptor instead.
func (*SecretValueRep) Descriptor() ([]byte, []int) {
	return file_server_v1_secret_proto_rawDescGZIP(), []int{6}
}

func (x *SecretValueRep) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_server_v1_secret_proto protoreflect.FileDescriptor

const file_server_v1_secret_proto_rawDesc = "" +
	"\n" +
	"\x16server_v1/secret.proto\x12\tserver_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\xd8\x01\n" +
	"\x0eSecretMetaMain\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12@\n" +
	"\vmodified_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"modifiedAt\x88\x01\x01\x12%\n" +
	"\x05scope\x18\x04 \x01(\v2\x0f.common.ScopeStR\x05scopeB\x0e\n" +
	"\f_modified_at\"E\n" +
	"\rSecretListReq\x12*\n" +
	"\x05scope\x18\x01 \x01(\v2\x0f.common.ScopeStH\x00R\x05scope\x88\x01\x01B\b\n" +
	"\x06_scope\"D\n" +
	"\rSecretListRep\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.server_v1.SecretMetaMainR\aresults\"_\n" +
	"\fSecretSetReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12%\n" +
	"\x05scope\x18\x03 \x01(\v2\x0f.common.ScopeStR\x05scope\"L\n" +
	"\x0fSecretDeleteReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x05scope\x18\x02 \x01(\v2\x0f.common.ScopeStR\x05scope\"N\n" +
	"\x11SecretGetValueReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x05scope\x18\x02 \x01(\v2\x0f.common.ScopeStR\x05scope\"&\n" +
	"\x0eSecretValueRep\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value2\x80\x03\n" +
	"\rSecretService\x12Q\n" +
	"\n" +
	"ListSecret\x12\x18.server_v1.SecretListReq\x1a\x18.server_v1.SecretListRep\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/secret\x12W\n" +
	"\tSetSecret\x12\x17.server_v1.SecretSetReq\x1a\x16.google.protobuf.Empty\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/secret/{name}\x12Z\n" +
	"\fDeleteSecret\x12\x1a.server_v1.SecretDeleteReq\x1a\x16.google.protobuf.Empty\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/secret/{name}\x12g\n" +
	"\x0eGetSecretValue\x12\x1c.server_v1.SecretGetValueReq\x1a\x19.server_v1.SecretValueRep\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/secret/{name}/valueB0Z.github.com/rendau/loom/api/server_v1;server_v1b\x06proto3"

var (
	file_server_v1_secret_proto_rawDescOnce sync.Once
	file_server_v1_secret_proto_rawDescData []byte
)

func file_server_v1_secret_proto_rawDescGZIP() []byte {
	file_server_v1_secret_proto_rawDescOnce.Do(func() {
		file_server_v1_secret_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_v1_secret_proto_rawDesc), len(file_server_v1_secret_proto_rawDesc)))
	})
	return file_server_v1_secret_proto_rawDescData
}

var file_server_v1_secret_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_server_v1_secret_proto_goTypes = []any{
	(*SecretMetaMain)(nil),        // 0: server_v1.SecretMetaMain
	(*SecretListReq)(nil),         // 1: server_v1.SecretListReq
	(*SecretListRep)(nil),         // 2: server_v1.SecretListRep
	(*SecretSetReq)(nil),          // 3: server_v1.SecretSetReq
	(*SecretDeleteReq)(nil),       // 4: server_v1.SecretDeleteReq
	(*SecretGetValueReq)(nil),     // 5: server_v1.SecretGetValueReq
	(*SecretValueRep)(nil),        // 6: server_v1.SecretValueRep
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*common.ScopeSt)(nil),        // 8: common.ScopeSt
	(*emptypb.Empty)(nil),         // 9: google.protobuf.Empty
}
var file_server_v1_secret_proto_depIdxs = []int32{
	7,  // 0: server_v1.SecretMetaMain.created_at:type_name -> google.protobuf.Timestamp
	7,  // 1: server_v1.SecretMetaMain.modified_at:type_name -> google.protobuf.Timestamp
	8,  // 2: server_v1.SecretMetaMain.scope:type_name -> common.ScopeSt
	8,  // 3: server_v1.SecretListReq.scope:type_name -> common.ScopeSt
	0,  // 4: server_v1.SecretListRep.results:type_name -> server_v1.SecretMetaMain
	8,  // 5: server_v1.SecretSetReq.scope:type_name -> common.ScopeSt
	8,  // 6: server_v1.SecretDeleteReq.scope:type_name -> common.ScopeSt
	8,  // 7: server_v1.SecretGetValueReq.scope:type_name -> common.ScopeSt
	1,  // 8: server_v1.SecretService.ListSecret:input_type -> server_v1.SecretListReq
	3,  // 9: server_v1.SecretService.SetSecret:input_type -> server_v1.SecretSetReq
	4,  // 10: server_v1.SecretService.DeleteSecret:input_type -> server_v1.SecretDeleteReq
	5,  // 11: server_v1.SecretService.GetSecretValue:input_type -> server_v1.SecretGetValueReq
	2,  // 12: server_v1.SecretService.ListSecret:output_type -> server_v1.SecretListRep
	9,  // 13: server_v1.SecretService.SetSecret:output_type -> google.protobuf.Empty
	9,  // 14: server_v1.SecretService.DeleteSecret:output_type -> google.protobuf.Empty
	6,  // 15: server_v1.SecretService.GetSecretValue:output_type -> server_v1.SecretValueRep
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_server_v1_secret_proto_init() }
func file_server_v1_secret_proto_init() {
	if File_server_v1_secret_proto != nil {
		return
	}
	file_server_v1_secret_proto_msgTypes[0].OneofWrappers = []any{}
	file_server_v1_secret_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_v1_secret_proto_rawDesc), len(file_server_v1_secret_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_v1_secret_proto_goTypes,
		DependencyIndexes: file_server_v1_secret_proto_depIdxs,
		MessageInfos:      file_server_v1_secret_proto_msgTypes,
	}.Build()
	File_server_v1_secret_proto = out.File
	file_server_v1_secret_proto_goTypes = nil
	file_server_v1_secret_proto_depIdxs = nil
}
