// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: server_v1/setting.proto

package server_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SettingMain struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// Скоуп: пусто — глобальный, иначе имя дага.
	DagName       string                 `protobuf:"bytes,3,opt,name=dag_name,json=dagName,proto3" json:"dag_name,omitempty"`
	ModifiedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingMain) Reset() {
	*x = SettingMain{}
	mi := &file_server_v1_setting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingMain) ProtoMessage() {}

func (x *SettingMain) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_setting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingMain.ProtoReflect.Descriptor instead.
func (*SettingMain) Descriptor() ([]byte, []int) {
	return file_server_v1_setting_proto_rawDescGZIP(), []int{0}
}

func (x *SettingMain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SettingMain) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SettingMain) GetDagName() string {
	if x != nil {
		return x.DagName
	}
	return ""
}

func (x *SettingMain) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

type SettingListReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Отсутствует — все скоупы; "" — только глобальные; имя дага — только его.
	DagName       *string `protobuf:"bytes,1,opt,name=dag_name,json=dagName,proto3,oneof" json:"dag_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingListReq) Reset() {
	*x = SettingListReq{}
	mi := &file_server_v1_setting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingListReq) ProtoMessage() {}

func (x *SettingListReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_setting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingListReq.ProtoReflect.Descriptor instead.
func (*SettingListReq) Descriptor() ([]byte, []int) {
	return file_server_v1_setting_proto_rawDescGZIP(), []int{1}
}

func (x *SettingListReq) GetDagName() string {
	if x != nil && x.DagName != nil {
		return *x.DagName
	}
	return ""
}

type SettingListRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SettingMain         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingListRep) Reset() {
	*x = SettingListRep{}
	mi := &file_server_v1_setting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingListRep) ProtoMessage() {}

func (x *SettingListRep) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_setting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingListRep.ProtoReflect.Descriptor instead.
func (*SettingListRep) Descriptor() ([]byte, []int) {
	return file_server_v1_setting_proto_rawDescGZIP(), []int{2}
}

func (x *SettingListRep) GetResults() []*SettingMain {
	if x != nil {
		return x.Results
	}
	return nil
}

type SettingSetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	DagName       string                 `protobuf:"bytes,3,opt,name=dag_name,json=dagName,proto3" json:"dag_name,omitempty"` // пусто — глобальный скоуп
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingSetReq) Reset() {
	*x = SettingSetReq{}
	mi := &file_server_v1_setting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingSetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingSetReq) ProtoMessage() {}

func (x *SettingSetReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_setting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingSetReq.ProtoReflect.Descriptor instead.
func (*SettingSetReq) Descriptor() ([]byte, []int) {
	return file_server_v1_setting_proto_rawDescGZIP(), []int{3}
}

func (x *SettingSetReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SettingSetReq) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SettingSetReq) GetDagName() string {
	if x != nil {
		return x.DagName
	}
	return ""
}

type SettingDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DagName       string                 `protobuf:"bytes,2,opt,name=dag_name,json=dagName,proto3" json:"dag_name,omitempty"` // имя дага; пустой скоуп не удаляется
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingDeleteReq) Reset() {
	*x = SettingDeleteReq{}
	mi := &file_server_v1_setting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingDeleteReq) ProtoMessage() {}

func (x *SettingDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_setting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingDeleteReq.ProtoReflect.Descriptor instead.
func (*SettingDeleteReq) Descriptor() ([]byte, []int) {
	return file_server_v1_setting_proto_rawDescGZIP(), []int{4}
}

func (x *SettingDeleteReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SettingDeleteReq) GetDagName() string {
	if x != nil {
		return x.DagName
	}
	return ""
}

var File_server_v1_setting_proto protoreflect.FileDescriptor

const file_server_v1_setting_proto_rawDesc = "" +
	"\n" +
	"\x17server_v1/setting.proto\x12\tserver_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8f\x01\n" +
	"\vSettingMain\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x19\n" +
	"\bdag_name\x18\x03 \x01(\tR\adagName\x12;\n" +
	"\vmodified_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"modifiedAt\"=\n" +
	"\x0eSettingListReq\x12\x1e\n" +
	"\bdag_name\x18\x01 \x01(\tH\x00R\adagName\x88\x01\x01B\v\n" +
	"\t_dag_name\"B\n" +
	"\x0eSettingListRep\x120\n" +
	"\aresults\x18\x01 \x03(\v2\x16.server_v1.SettingMainR\aresults\"T\n" +
	"\rSettingSetReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x19\n" +
	"\bdag_name\x18\x03 \x01(\tR\adagName\"A\n" +
	"\x10SettingDeleteReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bdag_name\x18\x02 \x01(\tR\adagName2\xa2\x02\n" +
	"\x0eSettingService\x12U\n" +
	"\vListSetting\x12\x19.server_v1.SettingListReq\x1a\x19.server_v1.SettingListRep\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/setting\x12Z\n" +
	"\n" +
	"SetSetting\x12\x18.server_v1.SettingSetReq\x1a\x16.google.protobuf.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\x1a\x0f/setting/{name}\x12]\n" +
	"\rDeleteSetting\x12\x1b.server_v1.SettingDeleteReq\x1a\x16.google.protobuf.Empty\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/setting/{name}B0Z.github.com/rendau/loom/api/server_v1;server_v1b\x06proto3"

var (
	file_server_v1_setting_proto_rawDescOnce sync.Once
	file_server_v1_setting_proto_rawDescData []byte
)

func file_server_v1_setting_proto_rawDescGZIP() []byte {
	file_server_v1_setting_proto_rawDescOnce.Do(func() {
		file_server_v1_setting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_v1_setting_proto_rawDesc), len(file_server_v1_setting_proto_rawDesc)))
	})
	return file_server_v1_setting_proto_rawDescData
}

var file_server_v1_setting_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_server_v1_setting_proto_goTypes = []any{
	(*SettingMain)(nil),           // 0: server_v1.SettingMain
	(*SettingListReq)(nil),        // 1: server_v1.SettingListReq
	(*SettingListRep)(nil),        // 2: server_v1.SettingListRep
	(*SettingSetReq)(nil),         // 3: server_v1.SettingSetReq
	(*SettingDeleteReq)(nil),      // 4: server_v1.SettingDeleteReq
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 6: google.protobuf.Empty
}
var file_server_v1_setting_proto_depIdxs = []int32{
	5, // 0: server_v1.SettingMain.modified_at:type_name -> google.protobuf.Timestamp
	0, // 1: server_v1.SettingListRep.results:type_name -> server_v1.SettingMain
	1, // 2: server_v1.SettingService.ListSetting:input_type -> server_v1.SettingListReq
	3, // 3: server_v1.SettingService.SetSetting:input_type -> server_v1.SettingSetReq
	4, // 4: server_v1.SettingService.DeleteSetting:input_type -> server_v1.SettingDeleteReq
	2, // 5: server_v1.SettingService.ListSetting:output_type -> server_v1.SettingListRep
	6, // 6: server_v1.SettingService.SetSetting:output_type -> google.protobuf.Empty
	6, // 7: server_v1.SettingService.DeleteSetting:output_type -> google.protobuf.Empty
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_server_v1_setting_proto_init() }
func file_server_v1_setting_proto_init() {
	if File_server_v1_setting_proto != nil {
		return
	}
	file_server_v1_setting_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_v1_setting_proto_rawDesc), len(file_server_v1_setting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_v1_setting_proto_goTypes,
		DependencyIndexes: file_server_v1_setting_proto_depIdxs,
		MessageInfos:      file_server_v1_setting_proto_msgTypes,
	}.Build()
	File_server_v1_setting_proto = out.File
	file_server_v1_setting_proto_goTypes = nil
	file_server_v1_setting_proto_depIdxs = nil
}
