// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: server_v1/setting.proto

package server_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SettingService_ListSetting_FullMethodName   = "/server_v1.SettingService/ListSetting"
	SettingService_SetSetting_FullMethodName    = "/server_v1.SettingService/SetSetting"
	SettingService_DeleteSetting_FullMethodName = "/server_v1.SettingService/DeleteSetting"
)

// SettingServiceClient is the client API for SettingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SettingService — настройки инсталляции в БД (вместо env-конфига):
// TTL ранов, retention по количеству, TTL k8s Job'ов и т.п.
// Скоуп: dag_name = "" — глобальный (менять может только admin), иначе
// уточнение для дага (перекрывает глобальное; права — как у переменных
// дага). Имена настроек фиксированы — произвольные сервер отклоняет.
type SettingServiceClient interface {
	// ListSetting возвращает настройки: сохранённые значения по скоупам.
	ListSetting(ctx context.Context, in *SettingListReq, opts ...grpc.CallOption) (*SettingListRep, error)
	// SetSetting задаёт значение настройки в скоупе.
	SetSetting(ctx context.Context, in *SettingSetReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// DeleteSetting удаляет уточнение настройки у дага (возврат к
	// глобальному значению). Глобальные значения не удаляются — только
	// меняются.
	DeleteSetting(ctx context.Context, in *SettingDeleteReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type settingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSettingServiceClient(cc grpc.ClientConnInterface) SettingServiceClient {
	return &settingServiceClient{cc}
}

func (c *settingServiceClient) ListSetting(ctx context.Context, in *SettingListReq, opts ...grpc.CallOption) (*SettingListRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettingListRep)
	err := c.cc.Invoke(ctx, SettingService_ListSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingServiceClient) SetSetting(ctx context.Context, in *SettingSetReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SettingService_SetSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingServiceClient) DeleteSetting(ctx context.Context, in *SettingDeleteReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SettingService_DeleteSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettingServiceServer is the server API for SettingService service.
// All implementations must embed UnimplementedSettingServiceServer
// for forward compatibility.
//
// SettingService — настройки инсталляции в БД (вместо env-конфига):
// TTL ранов, retention по количеству, TTL k8s Job'ов и т.п.
// Скоуп: dag_name = "" — глобальный (менять может только admin), иначе
// уточнение для дага (перекрывает глобальное; права — как у переменных
// дага). Имена настроек фиксированы — произвольные сервер отклоняет.
type SettingServiceServer interface {
	// ListSetting возвращает настройки: сохранённые значения по скоупам.
	ListSetting(context.Context, *SettingListReq) (*SettingListRep, error)
	// SetSetting задаёт значение настройки в скоупе.
	SetSetting(context.Context, *SettingSetReq) (*emptypb.Empty, error)
	// DeleteSetting удаляет уточнение настройки у дага (возврат к
	// глобальному значению). Глобальные значения не удаляются — только
	// меняются.
	DeleteSetting(context.Context, *SettingDeleteReq) (*emptypb.Empty, error)
	mustEmbedUnimplementedSettingServiceServer()
}

// UnimplementedSettingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSettingServiceServer struct{}

func (UnimplementedSettingServiceServer) ListSetting(context.Context, *SettingListReq) (*SettingListRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSetting not implemented")
}
func (UnimplementedSettingServiceServer) SetSetting(context.Context, *SettingSetReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetSetting not implemented")
}
func (UnimplementedSettingServiceServer) DeleteSetting(context.Context, *SettingDeleteReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSetting not implemented")
}
func (UnimplementedSettingServiceServer) mustEmbedUnimplementedSettingServiceServer() {}
func (UnimplementedSettingServiceServer) testEmbeddedByValue()                        {}

// UnsafeSettingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SettingServiceServer will
// result in compilation errors.
type UnsafeSettingServiceServer interface {
	mustEmbedUnimplementedSettingServiceServer()
}

func RegisterSettingServiceServer(s grpc.ServiceRegistrar, srv SettingServiceServer) {
	// If the following call pancis, it indicates UnimplementedSettingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SettingService_ServiceDesc, srv)
}

func _SettingService_ListSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServiceServer).ListSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingService_ListSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServiceServer).ListSetting(ctx, req.(*SettingListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingService_SetSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingSetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServiceServer).SetSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingService_SetSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServiceServer).SetSetting(ctx, req.(*SettingSetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingService_DeleteSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServiceServer).DeleteSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingService_DeleteSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServiceServer).DeleteSetting(ctx, req.(*SettingDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SettingService_ServiceDesc is the grpc.ServiceDesc for SettingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SettingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server_v1.SettingService",
	HandlerType: (*SettingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSetting",
			Handler:    _SettingService_ListSetting_Handler,
		},
		{
			MethodName: "SetSetting",
			Handler:    _SettingService_SetSetting_Handler,
		},
		{
			MethodName: "DeleteSetting",
			Handler:    _SettingService_DeleteSetting_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server_v1/setting.proto",
}
