// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: server_v1/task_log.proto

/*
Package server_v1 is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package server_v1

import (
	"context"
	"errors"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var (
	_ codes.Code
	_ io.Reader
	_ status.Status
	_ = errors.New
	_ = runtime.String
	_ = utilities.NewDoubleArray
	_ = metadata.Join
)

var filter_TaskLogService_ReadTaskLog_0 = &utilities.DoubleArray{Encoding: map[string]int{"run_id": 0, "task": 1, "attempt": 2}, Base: []int{1, 1, 2, 3, 0, 0, 0}, Check: []int{0, 1, 1, 1, 2, 3, 4}}

func request_TaskLogService_ReadTaskLog_0(ctx context.Context, marshaler runtime.Marshaler, client TaskLogServiceClient, req *http.Request, pathParams map[string]string) (TaskLogService_ReadTaskLogClient, runtime.ServerMetadata, error) {
	var (
		protoReq ReadTaskLogRequest
		metadata runtime.ServerMetadata
		err      error
	)
	if req.Body != nil {
		_, _ = io.Copy(io.Discard, req.Body)
	}
	val, ok := pathParams["run_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "run_id")
	}
	protoReq.RunId, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "run_id", err)
	}
	val, ok = pathParams["task"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "task")
	}
	protoReq.Task, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "task", err)
	}
	val, ok = pathParams["attempt"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "attempt")
	}
	protoReq.Attempt, err = runtime.Int32(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "attempt", err)
	}
	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_TaskLogService_ReadTaskLog_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	stream, err := client.ReadTaskLog(ctx, &protoReq)
	if err != nil {
		return nil, metadata, err
	}
	header, err := stream.Header()
	if err != nil {
		return nil, metadata, err
	}
	metadata.HeaderMD = header
	return stream, metadata, nil
}

// RegisterTaskLogServiceHandlerServer registers the http handlers for service TaskLogService to "mux".
// UnaryRPC     :call TaskLogServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterTaskLogServiceHandlerFromEndpoint instead.
// GRPC interceptors will not work for this type of registration. To use interceptors, you must use the "runtime.WithMiddlewares" option in the "runtime.NewServeMux" call.
func RegisterTaskLogServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server TaskLogServiceServer) error {
	mux.Handle(http.MethodGet, pattern_TaskLogService_ReadTaskLog_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		err := status.Error(codes.Unimplemented, "streaming calls are not yet supported in the in-process transport")
		_, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
		return
	})

	return nil
}

// RegisterTaskLogServiceHandlerFromEndpoint is same as RegisterTaskLogServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterTaskLogServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.NewClient(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()
	return RegisterTaskLogServiceHandler(ctx, mux, conn)
}

// RegisterTaskLogServiceHandler registers the http handlers for service TaskLogService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterTaskLogServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterTaskLogServiceHandlerClient(ctx, mux, NewTaskLogServiceClient(conn))
}

// RegisterTaskLogServiceHandlerClient registers the http handlers for service TaskLogService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "TaskLogServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "TaskLogServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "TaskLogServiceClient" to call the correct interceptors. This client ignores the HTTP middlewares.
func RegisterTaskLogServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client TaskLogServiceClient) error {
	mux.Handle(http.MethodGet, pattern_TaskLogService_ReadTaskLog_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/server_v1.TaskLogService/ReadTaskLog", runtime.WithHTTPPathPattern("/run/{run_id}/task/{task}/attempt/{attempt}/log"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_TaskLogService_ReadTaskLog_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_TaskLogService_ReadTaskLog_0(annotatedContext, mux, outboundMarshaler, w, req, func() (proto.Message, error) { return resp.Recv() }, mux.GetForwardResponseOptions()...)
	})
	return nil
}

var (
	pattern_TaskLogService_ReadTaskLog_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 1, 0, 4, 1, 5, 1, 2, 2, 1, 0, 4, 1, 5, 2, 2, 3, 1, 0, 4, 1, 5, 3, 2, 4}, []string{"run", "run_id", "task", "attempt", "log"}, ""))
)

var (
	forward_TaskLogService_ReadTaskLog_0 = runtime.ForwardResponseStream
)
