// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: server_v1/task_value.proto

package server_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskValueService_PushTaskValue_FullMethodName  = "/server_v1.TaskValueService/PushTaskValue"
	TaskValueService_PullTaskValue_FullMethodName  = "/server_v1.TaskValueService/PullTaskValue"
	TaskValueService_ListTaskValues_FullMethodName = "/server_v1.TaskValueService/ListTaskValues"
)

// TaskValueServiceClient is the client API for TaskValueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TaskValueService — мелкие значения тасков (аналог XCom):
// key-value через control plane, не через artifact-сервер. Скоуп значения —
// (run, task, key): ретрай таска перезаписывает его значения.
type TaskValueServiceClient interface {
	// PushTaskValue публикует значение таска (upsert по ключу). Требует
	// attempt-токен своего attempt'а; пуш от неактуальной (не текущей)
	// попытки отклоняется.
	PushTaskValue(ctx context.Context, in *TaskValuePushReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// PullTaskValue читает значение таска. Требует токен своего рана
	// (таски читают значения зависимостей).
	PullTaskValue(ctx context.Context, in *TaskValuePullReq, opts ...grpc.CallOption) (*TaskValuePullRep, error)
	// ListTaskValues возвращает все значения рана (админка).
	ListTaskValues(ctx context.Context, in *TaskValueListReq, opts ...grpc.CallOption) (*TaskValueListRep, error)
}

type taskValueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskValueServiceClient(cc grpc.ClientConnInterface) TaskValueServiceClient {
	return &taskValueServiceClient{cc}
}

func (c *taskValueServiceClient) PushTaskValue(ctx context.Context, in *TaskValuePushReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TaskValueService_PushTaskValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskValueServiceClient) PullTaskValue(ctx context.Context, in *TaskValuePullReq, opts ...grpc.CallOption) (*TaskValuePullRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskValuePullRep)
	err := c.cc.Invoke(ctx, TaskValueService_PullTaskValue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskValueServiceClient) ListTaskValues(ctx context.Context, in *TaskValueListReq, opts ...grpc.CallOption) (*TaskValueListRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskValueListRep)
	err := c.cc.Invoke(ctx, TaskValueService_ListTaskValues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskValueServiceServer is the server API for TaskValueService service.
// All implementations must embed UnimplementedTaskValueServiceServer
// for forward compatibility.
//
// TaskValueService — мелкие значения тасков (аналог XCom):
// key-value через control plane, не через artifact-сервер. Скоуп значения —
// (run, task, key): ретрай таска перезаписывает его значения.
type TaskValueServiceServer interface {
	// PushTaskValue публикует значение таска (upsert по ключу). Требует
	// attempt-токен своего attempt'а; пуш от неактуальной (не текущей)
	// попытки отклоняется.
	PushTaskValue(context.Context, *TaskValuePushReq) (*emptypb.Empty, error)
	// PullTaskValue читает значение таска. Требует токен своего рана
	// (таски читают значения зависимостей).
	PullTaskValue(context.Context, *TaskValuePullReq) (*TaskValuePullRep, error)
	// ListTaskValues возвращает все значения рана (админка).
	ListTaskValues(context.Context, *TaskValueListReq) (*TaskValueListRep, error)
	mustEmbedUnimplementedTaskValueServiceServer()
}

// UnimplementedTaskValueServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskValueServiceServer struct{}

func (UnimplementedTaskValueServiceServer) PushTaskValue(context.Context, *TaskValuePushReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushTaskValue not implemented")
}
func (UnimplementedTaskValueServiceServer) PullTaskValue(context.Context, *TaskValuePullReq) (*TaskValuePullRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullTaskValue not implemented")
}
func (UnimplementedTaskValueServiceServer) ListTaskValues(context.Context, *TaskValueListReq) (*TaskValueListRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTaskValues not implemented")
}
func (UnimplementedTaskValueServiceServer) mustEmbedUnimplementedTaskValueServiceServer() {}
func (UnimplementedTaskValueServiceServer) testEmbeddedByValue()                          {}

// UnsafeTaskValueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskValueServiceServer will
// result in compilation errors.
type UnsafeTaskValueServiceServer interface {
	mustEmbedUnimplementedTaskValueServiceServer()
}

func RegisterTaskValueServiceServer(s grpc.ServiceRegistrar, srv TaskValueServiceServer) {
	// If the following call pancis, it indicates UnimplementedTaskValueServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskValueService_ServiceDesc, srv)
}

func _TaskValueService_PushTaskValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskValuePushReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskValueServiceServer).PushTaskValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskValueService_PushTaskValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskValueServiceServer).PushTaskValue(ctx, req.(*TaskValuePushReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskValueService_PullTaskValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskValuePullReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskValueServiceServer).PullTaskValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskValueService_PullTaskValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskValueServiceServer).PullTaskValue(ctx, req.(*TaskValuePullReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskValueService_ListTaskValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskValueListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskValueServiceServer).ListTaskValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskValueService_ListTaskValues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskValueServiceServer).ListTaskValues(ctx, req.(*TaskValueListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskValueService_ServiceDesc is the grpc.ServiceDesc for TaskValueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskValueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server_v1.TaskValueService",
	HandlerType: (*TaskValueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushTaskValue",
			Handler:    _TaskValueService_PushTaskValue_Handler,
		},
		{
			MethodName: "PullTaskValue",
			Handler:    _TaskValueService_PullTaskValue_Handler,
		},
		{
			MethodName: "ListTaskValues",
			Handler:    _TaskValueService_ListTaskValues_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server_v1/task_value.proto",
}
