// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: server_v1/task_log.proto

package server_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskLogService_ReadTaskLog_FullMethodName = "/server_v1.TaskLogService/ReadTaskLog"
)

// TaskLogServiceClient is the client API for TaskLogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TaskLogService — чтение логов тасков через control plane (админка).
// Хранятся логи на artifact-сервере (artifact_v1.TaskLogService), control
// plane проксирует чтение — у админки и HTTP-gateway одна точка входа.
type TaskLogServiceClient interface {
	// ReadTaskLog читает лог попытки (по умолчанию с начала; after_seq
	// пропускает уже полученные строки — докачка после обрыва); при
	// follow=true стрим живёт до завершения попытки, отдавая новые строки по
	// мере поступления (live-логи в админке).
	ReadTaskLog(ctx context.Context, in *ReadTaskLogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadTaskLogResponse], error)
}

type taskLogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskLogServiceClient(cc grpc.ClientConnInterface) TaskLogServiceClient {
	return &taskLogServiceClient{cc}
}

func (c *taskLogServiceClient) ReadTaskLog(ctx context.Context, in *ReadTaskLogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadTaskLogResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskLogService_ServiceDesc.Streams[0], TaskLogService_ReadTaskLog_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadTaskLogRequest, ReadTaskLogResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskLogService_ReadTaskLogClient = grpc.ServerStreamingClient[ReadTaskLogResponse]

// TaskLogServiceServer is the server API for TaskLogService service.
// All implementations must embed UnimplementedTaskLogServiceServer
// for forward compatibility.
//
// TaskLogService — чтение логов тасков через control plane (админка).
// Хранятся логи на artifact-сервере (artifact_v1.TaskLogService), control
// plane проксирует чтение — у админки и HTTP-gateway одна точка входа.
type TaskLogServiceServer interface {
	// ReadTaskLog читает лог попытки (по умолчанию с начала; after_seq
	// пропускает уже полученные строки — докачка после обрыва); при
	// follow=true стрим живёт до завершения попытки, отдавая новые строки по
	// мере поступления (live-логи в админке).
	ReadTaskLog(*ReadTaskLogRequest, grpc.ServerStreamingServer[ReadTaskLogResponse]) error
	mustEmbedUnimplementedTaskLogServiceServer()
}

// UnimplementedTaskLogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskLogServiceServer struct{}

func (UnimplementedTaskLogServiceServer) ReadTaskLog(*ReadTaskLogRequest, grpc.ServerStreamingServer[ReadTaskLogResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ReadTaskLog not implemented")
}
func (UnimplementedTaskLogServiceServer) mustEmbedUnimplementedTaskLogServiceServer() {}
func (UnimplementedTaskLogServiceServer) testEmbeddedByValue()                        {}

// UnsafeTaskLogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskLogServiceServer will
// result in compilation errors.
type UnsafeTaskLogServiceServer interface {
	mustEmbedUnimplementedTaskLogServiceServer()
}

func RegisterTaskLogServiceServer(s grpc.ServiceRegistrar, srv TaskLogServiceServer) {
	// If the following call pancis, it indicates UnimplementedTaskLogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskLogService_ServiceDesc, srv)
}

func _TaskLogService_ReadTaskLog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadTaskLogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TaskLogServiceServer).ReadTaskLog(m, &grpc.GenericServerStream[ReadTaskLogRequest, ReadTaskLogResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskLogService_ReadTaskLogServer = grpc.ServerStreamingServer[ReadTaskLogResponse]

// TaskLogService_ServiceDesc is the grpc.ServiceDesc for TaskLogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskLogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server_v1.TaskLogService",
	HandlerType: (*TaskLogServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadTaskLog",
			Handler:       _TaskLogService_ReadTaskLog_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "server_v1/task_log.proto",
}
