// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: server_v1/user.proto

package server_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserListRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*UserMain            `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserListRep) Reset() {
	*x = UserListRep{}
	mi := &file_server_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserListRep) ProtoMessage() {}

func (x *UserListRep) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserListRep.ProtoReflect.Descriptor instead.
func (*UserListRep) Descriptor() ([]byte, []int) {
	return file_server_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserListRep) GetResults() []*UserMain {
	if x != nil {
		return x.Results
	}
	return nil
}

type UserCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // admin | user
	DagNames      []string               `protobuf:"bytes,4,rep,name=dag_names,json=dagNames,proto3" json:"dag_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreateReq) Reset() {
	*x = UserCreateReq{}
	mi := &file_server_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreateReq) ProtoMessage() {}

func (x *UserCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreateReq.ProtoReflect.Descriptor instead.
func (*UserCreateReq) Descriptor() ([]byte, []int) {
	return file_server_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserCreateReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserCreateReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserCreateReq) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserCreateReq) GetDagNames() []string {
	if x != nil {
		return x.DagNames
	}
	return nil
}

type UserUpdateReq struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Password *string                `protobuf:"bytes,2,opt,name=password,proto3,oneof" json:"password,omitempty"`
	Role     *string                `protobuf:"bytes,3,opt,name=role,proto3,oneof" json:"role,omitempty"`
	// Отсутствует — набор дагов не меняется; пустой список очищает его.
	DagNames      []string `protobuf:"bytes,4,rep,name=dag_names,json=dagNames,proto3" json:"dag_names,omitempty"`
	SetDagNames   bool     `protobuf:"varint,5,opt,name=set_dag_names,json=setDagNames,proto3" json:"set_dag_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateReq) Reset() {
	*x = UserUpdateReq{}
	mi := &file_server_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateReq) ProtoMessage() {}

func (x *UserUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateReq.ProtoReflect.Descriptor instead.
func (*UserUpdateReq) Descriptor() ([]byte, []int) {
	return file_server_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserUpdateReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserUpdateReq) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *UserUpdateReq) GetRole() string {
	if x != nil && x.Role != nil {
		return *x.Role
	}
	return ""
}

func (x *UserUpdateReq) GetDagNames() []string {
	if x != nil {
		return x.DagNames
	}
	return nil
}

func (x *UserUpdateReq) GetSetDagNames() bool {
	if x != nil {
		return x.SetDagNames
	}
	return false
}

type UserDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDeleteReq) Reset() {
	*x = UserDeleteReq{}
	mi := &file_server_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeleteReq) ProtoMessage() {}

func (x *UserDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeleteReq.ProtoReflect.Descriptor instead.
func (*UserDeleteReq) Descriptor() ([]byte, []int) {
	return file_server_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserDeleteReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_server_v1_user_proto protoreflect.FileDescriptor

const file_server_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x14server_v1/user.proto\x12\tserver_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x14server_v1/auth.proto\"<\n" +
	"\vUserListRep\x12-\n" +
	"\aresults\x18\x01 \x03(\v2\x13.server_v1.UserMainR\aresults\"x\n" +
	"\rUserCreateReq\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x1b\n" +
	"\tdag_names\x18\x04 \x03(\tR\bdagNames\"\xb0\x01\n" +
	"\rUserUpdateReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\bpassword\x18\x02 \x01(\tH\x00R\bpassword\x88\x01\x01\x12\x17\n" +
	"\x04role\x18\x03 \x01(\tH\x01R\x04role\x88\x01\x01\x12\x1b\n" +
	"\tdag_names\x18\x04 \x03(\tR\bdagNames\x12\"\n" +
	"\rset_dag_names\x18\x05 \x01(\bR\vsetDagNamesB\v\n" +
	"\t_passwordB\a\n" +
	"\x05_role\"\x1f\n" +
	"\rUserDeleteReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xd2\x02\n" +
	"\vUserService\x12I\n" +
	"\bListUser\x12\x16.google.protobuf.Empty\x1a\x16.server_v1.UserListRep\"\r\x82\xd3\xe4\x93\x02\a\x12\x05/user\x12M\n" +
	"\n" +
	"CreateUser\x12\x18.server_v1.UserCreateReq\x1a\x13.server_v1.UserMain\"\x10\x82\xd3\xe4\x93\x02\n" +
	":\x01*\"\x05/user\x12U\n" +
	"\n" +
	"UpdateUser\x12\x18.server_v1.UserUpdateReq\x1a\x16.google.protobuf.Empty\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\x1a\n" +
	"/user/{id}\x12R\n" +
	"\n" +
	"DeleteUser\x12\x18.server_v1.UserDeleteReq\x1a\x16.google.protobuf.Empty\"\x12\x82\xd3\xe4\x93\x02\f*\n" +
	"/user/{id}B0Z.github.com/rendau/loom/api/server_v1;server_v1b\x06proto3"

var (
	file_server_v1_user_proto_rawDescOnce sync.Once
	file_server_v1_user_proto_rawDescData []byte
)

func file_server_v1_user_proto_rawDescGZIP() []byte {
	file_server_v1_user_proto_rawDescOnce.Do(func() {
		file_server_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_v1_user_proto_rawDesc), len(file_server_v1_user_proto_rawDesc)))
	})
	return file_server_v1_user_proto_rawDescData
}

var file_server_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_server_v1_user_proto_goTypes = []any{
	(*UserListRep)(nil),   // 0: server_v1.UserListRep
	(*UserCreateReq)(nil), // 1: server_v1.UserCreateReq
	(*UserUpdateReq)(nil), // 2: server_v1.UserUpdateReq
	(*UserDeleteReq)(nil), // 3: server_v1.UserDeleteReq
	(*UserMain)(nil),      // 4: server_v1.UserMain
	(*emptypb.Empty)(nil), // 5: google.protobuf.Empty
}
var file_server_v1_user_proto_depIdxs = []int32{
	4, // 0: server_v1.UserListRep.results:type_name -> server_v1.UserMain
	5, // 1: server_v1.UserService.ListUser:input_type -> google.protobuf.Empty
	1, // 2: server_v1.UserService.CreateUser:input_type -> server_v1.UserCreateReq
	2, // 3: server_v1.UserService.UpdateUser:input_type -> server_v1.UserUpdateReq
	3, // 4: server_v1.UserService.DeleteUser:input_type -> server_v1.UserDeleteReq
	0, // 5: server_v1.UserService.ListUser:output_type -> server_v1.UserListRep
	4, // 6: server_v1.UserService.CreateUser:output_type -> server_v1.UserMain
	5, // 7: server_v1.UserService.UpdateUser:output_type -> google.protobuf.Empty
	5, // 8: server_v1.UserService.DeleteUser:output_type -> google.protobuf.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_server_v1_user_proto_init() }
func file_server_v1_user_proto_init() {
	if File_server_v1_user_proto != nil {
		return
	}
	file_server_v1_auth_proto_init()
	file_server_v1_user_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_v1_user_proto_rawDesc), len(file_server_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_v1_user_proto_goTypes,
		DependencyIndexes: file_server_v1_user_proto_depIdxs,
		MessageInfos:      file_server_v1_user_proto_msgTypes,
	}.Build()
	File_server_v1_user_proto = out.File
	file_server_v1_user_proto_goTypes = nil
	file_server_v1_user_proto_depIdxs = nil
}
