// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: server_v1/variable.proto

package server_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VariableService_ListVariable_FullMethodName   = "/server_v1.VariableService/ListVariable"
	VariableService_SetVariable_FullMethodName    = "/server_v1.VariableService/SetVariable"
	VariableService_DeleteVariable_FullMethodName = "/server_v1.VariableService/DeleteVariable"
)

// VariableServiceClient is the client API for VariableService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VariableService — переменные для env-инъекции в поды тасков: как секреты,
// но значения хранятся открыто и видны в админке.
// Скоуп: dag_name = "" — глобальный, иначе локальный для дага; локальный
// перекрывает глобальный с тем же именем при запуске попытки.
type VariableServiceClient interface {
	// ListVariable возвращает переменные со значениями.
	ListVariable(ctx context.Context, in *VariableListReq, opts ...grpc.CallOption) (*VariableListRep, error)
	// SetVariable создаёт переменную или перезаписывает значение существующей.
	SetVariable(ctx context.Context, in *VariableSetReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteVariable(ctx context.Context, in *VariableDeleteReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type variableServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVariableServiceClient(cc grpc.ClientConnInterface) VariableServiceClient {
	return &variableServiceClient{cc}
}

func (c *variableServiceClient) ListVariable(ctx context.Context, in *VariableListReq, opts ...grpc.CallOption) (*VariableListRep, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VariableListRep)
	err := c.cc.Invoke(ctx, VariableService_ListVariable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variableServiceClient) SetVariable(ctx context.Context, in *VariableSetReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, VariableService_SetVariable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *variableServiceClient) DeleteVariable(ctx context.Context, in *VariableDeleteReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, VariableService_DeleteVariable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VariableServiceServer is the server API for VariableService service.
// All implementations must embed UnimplementedVariableServiceServer
// for forward compatibility.
//
// VariableService — переменные для env-инъекции в поды тасков: как секреты,
// но значения хранятся открыто и видны в админке.
// Скоуп: dag_name = "" — глобальный, иначе локальный для дага; локальный
// перекрывает глобальный с тем же именем при запуске попытки.
type VariableServiceServer interface {
	// ListVariable возвращает переменные со значениями.
	ListVariable(context.Context, *VariableListReq) (*VariableListRep, error)
	// SetVariable создаёт переменную или перезаписывает значение существующей.
	SetVariable(context.Context, *VariableSetReq) (*emptypb.Empty, error)
	DeleteVariable(context.Context, *VariableDeleteReq) (*emptypb.Empty, error)
	mustEmbedUnimplementedVariableServiceServer()
}

// UnimplementedVariableServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVariableServiceServer struct{}

func (UnimplementedVariableServiceServer) ListVariable(context.Context, *VariableListReq) (*VariableListRep, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVariable not implemented")
}
func (UnimplementedVariableServiceServer) SetVariable(context.Context, *VariableSetReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVariable not implemented")
}
func (UnimplementedVariableServiceServer) DeleteVariable(context.Context, *VariableDeleteReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVariable not implemented")
}
func (UnimplementedVariableServiceServer) mustEmbedUnimplementedVariableServiceServer() {}
func (UnimplementedVariableServiceServer) testEmbeddedByValue()                         {}

// UnsafeVariableServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VariableServiceServer will
// result in compilation errors.
type UnsafeVariableServiceServer interface {
	mustEmbedUnimplementedVariableServiceServer()
}

func RegisterVariableServiceServer(s grpc.ServiceRegistrar, srv VariableServiceServer) {
	// If the following call pancis, it indicates UnimplementedVariableServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VariableService_ServiceDesc, srv)
}

func _VariableService_ListVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VariableListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariableServiceServer).ListVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariableService_ListVariable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariableServiceServer).ListVariable(ctx, req.(*VariableListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariableService_SetVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VariableSetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariableServiceServer).SetVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariableService_SetVariable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariableServiceServer).SetVariable(ctx, req.(*VariableSetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VariableService_DeleteVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VariableDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VariableServiceServer).DeleteVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VariableService_DeleteVariable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VariableServiceServer).DeleteVariable(ctx, req.(*VariableDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

// VariableService_ServiceDesc is the grpc.ServiceDesc for VariableService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VariableService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server_v1.VariableService",
	HandlerType: (*VariableServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListVariable",
			Handler:    _VariableService_ListVariable_Handler,
		},
		{
			MethodName: "SetVariable",
			Handler:    _VariableService_SetVariable_Handler,
		},
		{
			MethodName: "DeleteVariable",
			Handler:    _VariableService_DeleteVariable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server_v1/variable.proto",
}
