// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: server_v1/variable.proto

package server_v1

import (
	common "github.com/rendau/loom/api/common"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VariableMain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Scope         *common.ScopeSt        `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ModifiedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=modified_at,json=modifiedAt,proto3,oneof" json:"modified_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariableMain) Reset() {
	*x = VariableMain{}
	mi := &file_server_v1_variable_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariableMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableMain) ProtoMessage() {}

func (x *VariableMain) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_variable_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableMain.ProtoReflect.Descriptor instead.
func (*VariableMain) Descriptor() ([]byte, []int) {
	return file_server_v1_variable_proto_rawDescGZIP(), []int{0}
}

func (x *VariableMain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VariableMain) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *VariableMain) GetScope() *common.ScopeSt {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *VariableMain) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *VariableMain) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ModifiedAt
	}
	return nil
}

type VariableListReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Отсутствует — все скоупы; иначе — только указанный.
	Scope         *common.ScopeSt `protobuf:"bytes,1,opt,name=scope,proto3,oneof" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariableListReq) Reset() {
	*x = VariableListReq{}
	mi := &file_server_v1_variable_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariableListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableListReq) ProtoMessage() {}

func (x *VariableListReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_variable_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableListReq.ProtoReflect.Descriptor instead.
func (*VariableListReq) Descriptor() ([]byte, []int) {
	return file_server_v1_variable_proto_rawDescGZIP(), []int{1}
}

func (x *VariableListReq) GetScope() *common.ScopeSt {
	if x != nil {
		return x.Scope
	}
	return nil
}

type VariableListRep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*VariableMain        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariableListRep) Reset() {
	*x = VariableListRep{}
	mi := &file_server_v1_variable_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariableListRep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableListRep) ProtoMessage() {}

func (x *VariableListRep) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_variable_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableListRep.ProtoReflect.Descriptor instead.
func (*VariableListRep) Descriptor() ([]byte, []int) {
	return file_server_v1_variable_proto_rawDescGZIP(), []int{2}
}

func (x *VariableListRep) GetResults() []*VariableMain {
	if x != nil {
		return x.Results
	}
	return nil
}

type VariableSetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Scope         *common.ScopeSt        `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"` // пустой — глобальный скоуп
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariableSetReq) Reset() {
	*x = VariableSetReq{}
	mi := &file_server_v1_variable_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariableSetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableSetReq) ProtoMessage() {}

func (x *VariableSetReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_variable_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableSetReq.ProtoReflect.Descriptor instead.
func (*VariableSetReq) Descriptor() ([]byte, []int) {
	return file_server_v1_variable_proto_rawDescGZIP(), []int{3}
}

func (x *VariableSetReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VariableSetReq) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *VariableSetReq) GetScope() *common.ScopeSt {
	if x != nil {
		return x.Scope
	}
	return nil
}

type VariableDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Scope         *common.ScopeSt        `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"` // пустой — глобальный скоуп
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariableDeleteReq) Reset() {
	*x = VariableDeleteReq{}
	mi := &file_server_v1_variable_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariableDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableDeleteReq) ProtoMessage() {}

func (x *VariableDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_variable_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableDeleteReq.ProtoReflect.Descriptor instead.
func (*VariableDeleteReq) Descriptor() ([]byte, []int) {
	return file_server_v1_variable_proto_rawDescGZIP(), []int{4}
}

func (x *VariableDeleteReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VariableDeleteReq) GetScope() *common.ScopeSt {
	if x != nil {
		return x.Scope
	}
	return nil
}

type VariableMoveReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Scope         *common.ScopeSt        `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`                    // откуда; пустой — глобальный скоуп
	ToScope       *common.ScopeSt        `protobuf:"bytes,3,opt,name=to_scope,json=toScope,proto3" json:"to_scope,omitempty"` // куда; пустой — глобальный скоуп
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariableMoveReq) Reset() {
	*x = VariableMoveReq{}
	mi := &file_server_v1_variable_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariableMoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariableMoveReq) ProtoMessage() {}

func (x *VariableMoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_server_v1_variable_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariableMoveReq.ProtoReflect.Descriptor instead.
func (*VariableMoveReq) Descriptor() ([]byte, []int) {
	return file_server_v1_variable_proto_rawDescGZIP(), []int{5}
}

func (x *VariableMoveReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VariableMoveReq) GetScope() *common.ScopeSt {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *VariableMoveReq) GetToScope() *common.ScopeSt {
	if x != nil {
		return x.ToScope
	}
	return nil
}

var File_server_v1_variable_proto protoreflect.FileDescriptor

const file_server_v1_variable_proto_rawDesc = "" +
	"\n" +
	"\x18server_v1/variable.proto\x12\tserver_v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13common/common.proto\"\xec\x01\n" +
	"\fVariableMain\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12%\n" +
	"\x05scope\x18\x03 \x01(\v2\x0f.common.ScopeStR\x05scope\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12@\n" +
	"\vmodified_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"modifiedAt\x88\x01\x01B\x0e\n" +
	"\f_modified_at\"G\n" +
	"\x0fVariableListReq\x12*\n" +
	"\x05scope\x18\x01 \x01(\v2\x0f.common.ScopeStH\x00R\x05scope\x88\x01\x01B\b\n" +
	"\x06_scope\"D\n" +
	"\x0fVariableListRep\x121\n" +
	"\aresults\x18\x01 \x03(\v2\x17.server_v1.VariableMainR\aresults\"a\n" +
	"\x0eVariableSetReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12%\n" +
	"\x05scope\x18\x03 \x01(\v2\x0f.common.ScopeStR\x05scope\"N\n" +
	"\x11VariableDeleteReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x05scope\x18\x02 \x01(\v2\x0f.common.ScopeStR\x05scope\"x\n" +
	"\x0fVariableMoveReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x05scope\x18\x02 \x01(\v2\x0f.common.ScopeStR\x05scope\x12*\n" +
	"\bto_scope\x18\x03 \x01(\v2\x0f.common.ScopeStR\atoScope2\x93\x03\n" +
	"\x0fVariableService\x12Y\n" +
	"\fListVariable\x12\x1a.server_v1.VariableListReq\x1a\x1a.server_v1.VariableListRep\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/variable\x12]\n" +
	"\vSetVariable\x12\x19.server_v1.VariableSetReq\x1a\x16.google.protobuf.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\x1a\x10/variable/{name}\x12`\n" +
	"\x0eDeleteVariable\x12\x1c.server_v1.VariableDeleteReq\x1a\x16.google.protobuf.Empty\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/variable/{name}\x12d\n" +
	"\fMoveVariable\x12\x1a.server_v1.VariableMoveReq\x1a\x16.google.protobuf.Empty\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/variable/{name}/moveB0Z.github.com/rendau/loom/api/server_v1;server_v1b\x06proto3"

var (
	file_server_v1_variable_proto_rawDescOnce sync.Once
	file_server_v1_variable_proto_rawDescData []byte
)

func file_server_v1_variable_proto_rawDescGZIP() []byte {
	file_server_v1_variable_proto_rawDescOnce.Do(func() {
		file_server_v1_variable_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_v1_variable_proto_rawDesc), len(file_server_v1_variable_proto_rawDesc)))
	})
	return file_server_v1_variable_proto_rawDescData
}

var file_server_v1_variable_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_server_v1_variable_proto_goTypes = []any{
	(*VariableMain)(nil),          // 0: server_v1.VariableMain
	(*VariableListReq)(nil),       // 1: server_v1.VariableListReq
	(*VariableListRep)(nil),       // 2: server_v1.VariableListRep
	(*VariableSetReq)(nil),        // 3: server_v1.VariableSetReq
	(*VariableDeleteReq)(nil),     // 4: server_v1.VariableDeleteReq
	(*VariableMoveReq)(nil),       // 5: server_v1.VariableMoveReq
	(*common.ScopeSt)(nil),        // 6: common.ScopeSt
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_server_v1_variable_proto_depIdxs = []int32{
	6,  // 0: server_v1.VariableMain.scope:type_name -> common.ScopeSt
	7,  // 1: server_v1.VariableMain.created_at:type_name -> google.protobuf.Timestamp
	7,  // 2: server_v1.VariableMain.modified_at:type_name -> google.protobuf.Timestamp
	6,  // 3: server_v1.VariableListReq.scope:type_name -> common.ScopeSt
	0,  // 4: server_v1.VariableListRep.results:type_name -> server_v1.VariableMain
	6,  // 5: server_v1.VariableSetReq.scope:type_name -> common.ScopeSt
	6,  // 6: server_v1.VariableDeleteReq.scope:type_name -> common.ScopeSt
	6,  // 7: server_v1.VariableMoveReq.scope:type_name -> common.ScopeSt
	6,  // 8: server_v1.VariableMoveReq.to_scope:type_name -> common.ScopeSt
	1,  // 9: server_v1.VariableService.ListVariable:input_type -> server_v1.VariableListReq
	3,  // 10: server_v1.VariableService.SetVariable:input_type -> server_v1.VariableSetReq
	4,  // 11: server_v1.VariableService.DeleteVariable:input_type -> server_v1.VariableDeleteReq
	5,  // 12: server_v1.VariableService.MoveVariable:input_type -> server_v1.VariableMoveReq
	2,  // 13: server_v1.VariableService.ListVariable:output_type -> server_v1.VariableListRep
	8,  // 14: server_v1.VariableService.SetVariable:output_type -> google.protobuf.Empty
	8,  // 15: server_v1.VariableService.DeleteVariable:output_type -> google.protobuf.Empty
	8,  // 16: server_v1.VariableService.MoveVariable:output_type -> google.protobuf.Empty
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_server_v1_variable_proto_init() }
func file_server_v1_variable_proto_init() {
	if File_server_v1_variable_proto != nil {
		return
	}
	file_server_v1_variable_proto_msgTypes[0].OneofWrappers = []any{}
	file_server_v1_variable_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_v1_variable_proto_rawDesc), len(file_server_v1_variable_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_v1_variable_proto_goTypes,
		DependencyIndexes: file_server_v1_variable_proto_depIdxs,
		MessageInfos:      file_server_v1_variable_proto_msgTypes,
	}.Build()
	File_server_v1_variable_proto = out.File
	file_server_v1_variable_proto_goTypes = nil
	file_server_v1_variable_proto_depIdxs = nil
}
