// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: artifact_v1/artifact.proto

package artifact_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArtifactService_WriteArtifact_FullMethodName      = "/artifact_v1.ArtifactService/WriteArtifact"
	ArtifactService_ReadArtifact_FullMethodName       = "/artifact_v1.ArtifactService/ReadArtifact"
	ArtifactService_StatArtifact_FullMethodName       = "/artifact_v1.ArtifactService/StatArtifact"
	ArtifactService_AbortArtifact_FullMethodName      = "/artifact_v1.ArtifactService/AbortArtifact"
	ArtifactService_FinishAttempt_FullMethodName      = "/artifact_v1.ArtifactService/FinishAttempt"
	ArtifactService_DeleteRunArtifacts_FullMethodName = "/artifact_v1.ArtifactService/DeleteRunArtifacts"
)

// ArtifactServiceClient is the client API for ArtifactService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ArtifactService — data plane: обмен артефактами (стримами данных) между
// тасками рана.
//
// Жизненный цикл артефакта: writing → committed | aborted.
// Артефакт скоупится на попытку таска: (run_id, task, attempt, name) —
// ретрай таска пишет свои артефакты новой попыткой, не трогая прошлые.
type ArtifactServiceClient interface {
	// WriteArtifact пишет артефакт клиентским стримом: первое сообщение —
	// header, далее chunk'и, последнее — commit. Закрытие стрима без
	// commit трактуется как abort (писатель упал).
	WriteArtifact(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteArtifactRequest, WriteArtifactResponse], error)
	// ReadArtifact читает артефакт с offset. При follow=true читатель,
	// догнавший хвост пишущегося артефакта, ждёт новых данных; поток
	// завершается только после commit записи, а abort записи возвращает
	// читателю ошибку ABORTED.
	ReadArtifact(ctx context.Context, in *ReadArtifactRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadArtifactResponse], error)
	StatArtifact(ctx context.Context, in *StatArtifactRequest, opts ...grpc.CallOption) (*StatArtifactResponse, error)
	// AbortArtifact принудительно abort'ит запись — используется control
	// plane'ом для стримов умерших attempt'ов.
	AbortArtifact(ctx context.Context, in *AbortArtifactRequest, opts ...grpc.CallOption) (*AbortArtifactResponse, error)
	// FinishAttempt помечает попытку таска завершённой: abort её оставшимся
	// записям, читатели несозданных артефактов получают NOT_FOUND вместо
	// вечного ожидания. Идемпотентен: SDK вызывает его по завершении таска,
	// control plane повторяет как страховку при смерти пода.
	FinishAttempt(ctx context.Context, in *FinishAttemptRequest, opts ...grpc.CallOption) (*FinishAttemptResponse, error)
	// DeleteRunArtifacts удаляет все артефакты рана (retention).
	DeleteRunArtifacts(ctx context.Context, in *DeleteRunArtifactsRequest, opts ...grpc.CallOption) (*DeleteRunArtifactsResponse, error)
}

type artifactServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArtifactServiceClient(cc grpc.ClientConnInterface) ArtifactServiceClient {
	return &artifactServiceClient{cc}
}

func (c *artifactServiceClient) WriteArtifact(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteArtifactRequest, WriteArtifactResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ArtifactService_ServiceDesc.Streams[0], ArtifactService_WriteArtifact_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WriteArtifactRequest, WriteArtifactResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArtifactService_WriteArtifactClient = grpc.ClientStreamingClient[WriteArtifactRequest, WriteArtifactResponse]

func (c *artifactServiceClient) ReadArtifact(ctx context.Context, in *ReadArtifactRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadArtifactResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ArtifactService_ServiceDesc.Streams[1], ArtifactService_ReadArtifact_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadArtifactRequest, ReadArtifactResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArtifactService_ReadArtifactClient = grpc.ServerStreamingClient[ReadArtifactResponse]

func (c *artifactServiceClient) StatArtifact(ctx context.Context, in *StatArtifactRequest, opts ...grpc.CallOption) (*StatArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatArtifactResponse)
	err := c.cc.Invoke(ctx, ArtifactService_StatArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactServiceClient) AbortArtifact(ctx context.Context, in *AbortArtifactRequest, opts ...grpc.CallOption) (*AbortArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortArtifactResponse)
	err := c.cc.Invoke(ctx, ArtifactService_AbortArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactServiceClient) FinishAttempt(ctx context.Context, in *FinishAttemptRequest, opts ...grpc.CallOption) (*FinishAttemptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinishAttemptResponse)
	err := c.cc.Invoke(ctx, ArtifactService_FinishAttempt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactServiceClient) DeleteRunArtifacts(ctx context.Context, in *DeleteRunArtifactsRequest, opts ...grpc.CallOption) (*DeleteRunArtifactsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRunArtifactsResponse)
	err := c.cc.Invoke(ctx, ArtifactService_DeleteRunArtifacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArtifactServiceServer is the server API for ArtifactService service.
// All implementations must embed UnimplementedArtifactServiceServer
// for forward compatibility.
//
// ArtifactService — data plane: обмен артефактами (стримами данных) между
// тасками рана.
//
// Жизненный цикл артефакта: writing → committed | aborted.
// Артефакт скоупится на попытку таска: (run_id, task, attempt, name) —
// ретрай таска пишет свои артефакты новой попыткой, не трогая прошлые.
type ArtifactServiceServer interface {
	// WriteArtifact пишет артефакт клиентским стримом: первое сообщение —
	// header, далее chunk'и, последнее — commit. Закрытие стрима без
	// commit трактуется как abort (писатель упал).
	WriteArtifact(grpc.ClientStreamingServer[WriteArtifactRequest, WriteArtifactResponse]) error
	// ReadArtifact читает артефакт с offset. При follow=true читатель,
	// догнавший хвост пишущегося артефакта, ждёт новых данных; поток
	// завершается только после commit записи, а abort записи возвращает
	// читателю ошибку ABORTED.
	ReadArtifact(*ReadArtifactRequest, grpc.ServerStreamingServer[ReadArtifactResponse]) error
	StatArtifact(context.Context, *StatArtifactRequest) (*StatArtifactResponse, error)
	// AbortArtifact принудительно abort'ит запись — используется control
	// plane'ом для стримов умерших attempt'ов.
	AbortArtifact(context.Context, *AbortArtifactRequest) (*AbortArtifactResponse, error)
	// FinishAttempt помечает попытку таска завершённой: abort её оставшимся
	// записям, читатели несозданных артефактов получают NOT_FOUND вместо
	// вечного ожидания. Идемпотентен: SDK вызывает его по завершении таска,
	// control plane повторяет как страховку при смерти пода.
	FinishAttempt(context.Context, *FinishAttemptRequest) (*FinishAttemptResponse, error)
	// DeleteRunArtifacts удаляет все артефакты рана (retention).
	DeleteRunArtifacts(context.Context, *DeleteRunArtifactsRequest) (*DeleteRunArtifactsResponse, error)
	mustEmbedUnimplementedArtifactServiceServer()
}

// UnimplementedArtifactServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArtifactServiceServer struct{}

func (UnimplementedArtifactServiceServer) WriteArtifact(grpc.ClientStreamingServer[WriteArtifactRequest, WriteArtifactResponse]) error {
	return status.Errorf(codes.Unimplemented, "method WriteArtifact not implemented")
}
func (UnimplementedArtifactServiceServer) ReadArtifact(*ReadArtifactRequest, grpc.ServerStreamingServer[ReadArtifactResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ReadArtifact not implemented")
}
func (UnimplementedArtifactServiceServer) StatArtifact(context.Context, *StatArtifactRequest) (*StatArtifactResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatArtifact not implemented")
}
func (UnimplementedArtifactServiceServer) AbortArtifact(context.Context, *AbortArtifactRequest) (*AbortArtifactResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbortArtifact not implemented")
}
func (UnimplementedArtifactServiceServer) FinishAttempt(context.Context, *FinishAttemptRequest) (*FinishAttemptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishAttempt not implemented")
}
func (UnimplementedArtifactServiceServer) DeleteRunArtifacts(context.Context, *DeleteRunArtifactsRequest) (*DeleteRunArtifactsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRunArtifacts not implemented")
}
func (UnimplementedArtifactServiceServer) mustEmbedUnimplementedArtifactServiceServer() {}
func (UnimplementedArtifactServiceServer) testEmbeddedByValue()                         {}

// UnsafeArtifactServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArtifactServiceServer will
// result in compilation errors.
type UnsafeArtifactServiceServer interface {
	mustEmbedUnimplementedArtifactServiceServer()
}

func RegisterArtifactServiceServer(s grpc.ServiceRegistrar, srv ArtifactServiceServer) {
	// If the following call pancis, it indicates UnimplementedArtifactServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArtifactService_ServiceDesc, srv)
}

func _ArtifactService_WriteArtifact_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ArtifactServiceServer).WriteArtifact(&grpc.GenericServerStream[WriteArtifactRequest, WriteArtifactResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArtifactService_WriteArtifactServer = grpc.ClientStreamingServer[WriteArtifactRequest, WriteArtifactResponse]

func _ArtifactService_ReadArtifact_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadArtifactRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ArtifactServiceServer).ReadArtifact(m, &grpc.GenericServerStream[ReadArtifactRequest, ReadArtifactResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArtifactService_ReadArtifactServer = grpc.ServerStreamingServer[ReadArtifactResponse]

func _ArtifactService_StatArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactServiceServer).StatArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactService_StatArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactServiceServer).StatArtifact(ctx, req.(*StatArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactService_AbortArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactServiceServer).AbortArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactService_AbortArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactServiceServer).AbortArtifact(ctx, req.(*AbortArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactService_FinishAttempt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishAttemptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactServiceServer).FinishAttempt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactService_FinishAttempt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactServiceServer).FinishAttempt(ctx, req.(*FinishAttemptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactService_DeleteRunArtifacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRunArtifactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactServiceServer).DeleteRunArtifacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactService_DeleteRunArtifacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactServiceServer).DeleteRunArtifacts(ctx, req.(*DeleteRunArtifactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArtifactService_ServiceDesc is the grpc.ServiceDesc for ArtifactService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArtifactService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "artifact_v1.ArtifactService",
	HandlerType: (*ArtifactServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StatArtifact",
			Handler:    _ArtifactService_StatArtifact_Handler,
		},
		{
			MethodName: "AbortArtifact",
			Handler:    _ArtifactService_AbortArtifact_Handler,
		},
		{
			MethodName: "FinishAttempt",
			Handler:    _ArtifactService_FinishAttempt_Handler,
		},
		{
			MethodName: "DeleteRunArtifacts",
			Handler:    _ArtifactService_DeleteRunArtifacts_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WriteArtifact",
			Handler:       _ArtifactService_WriteArtifact_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ReadArtifact",
			Handler:       _ArtifactService_ReadArtifact_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "artifact_v1/artifact.proto",
}
