// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: artifact_v1/artifact.proto

package artifact_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArtifactState int32

const (
	ArtifactState_ARTIFACT_STATE_UNSPECIFIED ArtifactState = 0
	ArtifactState_ARTIFACT_STATE_WRITING     ArtifactState = 1
	ArtifactState_ARTIFACT_STATE_COMMITTED   ArtifactState = 2
	ArtifactState_ARTIFACT_STATE_ABORTED     ArtifactState = 3
)

// Enum value maps for ArtifactState.
var (
	ArtifactState_name = map[int32]string{
		0: "ARTIFACT_STATE_UNSPECIFIED",
		1: "ARTIFACT_STATE_WRITING",
		2: "ARTIFACT_STATE_COMMITTED",
		3: "ARTIFACT_STATE_ABORTED",
	}
	ArtifactState_value = map[string]int32{
		"ARTIFACT_STATE_UNSPECIFIED": 0,
		"ARTIFACT_STATE_WRITING":     1,
		"ARTIFACT_STATE_COMMITTED":   2,
		"ARTIFACT_STATE_ABORTED":     3,
	}
)

func (x ArtifactState) Enum() *ArtifactState {
	p := new(ArtifactState)
	*p = x
	return p
}

func (x ArtifactState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArtifactState) Descriptor() protoreflect.EnumDescriptor {
	return file_artifact_v1_artifact_proto_enumTypes[0].Descriptor()
}

func (ArtifactState) Type() protoreflect.EnumType {
	return &file_artifact_v1_artifact_proto_enumTypes[0]
}

func (x ArtifactState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArtifactState.Descriptor instead.
func (ArtifactState) EnumDescriptor() ([]byte, []int) {
	return file_artifact_v1_artifact_proto_rawDescGZIP(), []int{0}
}

type ArtifactRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Task          string                 `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	Attempt       int32                  `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactRef) Reset() {
	*x = ArtifactRef{}
	mi := &file_artifact_v1_artifact_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactRef) ProtoMessage() {}

func (x *ArtifactRef) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_artifact_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactRef.ProtoReflect.Descriptor instead.
func (*ArtifactRef) Descriptor() ([]byte, []int) {
	return file_artifact_v1_artifact_proto_rawDescGZIP(), []int{0}
}

func (x *ArtifactRef) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ArtifactRef) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *ArtifactRef) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *ArtifactRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WriteArtifactRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*WriteArtifactRequest_Header
	//	*WriteArtifactRequest_Chunk
	//	*WriteArtifactRequest_Commit
	//	*WriteArtifactRequest_Abort
	Msg           isWriteArtifactRequest_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteArtifactRequest) Reset() {
	*x = WriteArtifactRequest{}
	mi := &file_artifact_v1_artifact_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteArtifactRequest) ProtoMessage() {}

func (x *WriteArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_artifact_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteArtifactRequest.ProtoReflect.Descriptor instead.
func (*WriteArtifactRequest) Descriptor() ([]byte, []int) {
	return file_artifact_v1_artifact_proto_rawDescGZIP(), []int{1}
}

func (x *WriteArtifactRequest) GetMsg() isWriteArtifactRequest_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *WriteArtifactRequest) GetHeader() *WriteArtifactHeader {
	if x != nil {
		if x, ok := x.Msg.(*WriteArtifactRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *WriteArtifactRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Msg.(*WriteArtifactRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *WriteArtifactRequest) GetCommit() bool {
	if x != nil {
		if x, ok := x.Msg.(*WriteArtifactRequest_Commit); ok {
			return x.Commit
		}
	}
	return false
}

func (x *WriteArtifactRequest) GetAbort() bool {
	if x != nil {
		if x, ok := x.Msg.(*WriteArtifactRequest_Abort); ok {
			return x.Abort
		}
	}
	return false
}

type isWriteArtifactRequest_Msg interface {
	isWriteArtifactRequest_Msg()
}

type WriteArtifactRequest_Header struct {
	Header *WriteArtifactHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type WriteArtifactRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

type WriteArtifactRequest_Commit struct {
	Commit bool `protobuf:"varint,3,opt,name=commit,proto3,oneof"`
}

type WriteArtifactRequest_Abort struct {
	Abort bool `protobuf:"varint,4,opt,name=abort,proto3,oneof"`
}

func (*WriteArtifactRequest_Header) isWriteArtifactRequest_Msg() {}

func (*WriteArtifactRequest_Chunk) isWriteArtifactRequest_Msg() {}

func (*WriteArtifactRequest_Commit) isWriteArtifactRequest_Msg() {}

func (*WriteArtifactRequest_Abort) isWriteArtifactRequest_Msg() {}

type WriteArtifactHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ref   *ArtifactRef           `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	// resume — реконнект писателя: продолжить writing-стрим с текущего
	// размера (ack на header — точка продолжения); false — новая запись.
	Resume        bool `protobuf:"varint,2,opt,name=resume,proto3" json:"resume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteArtifactHeader) Reset() {
	*x = WriteArtifactHeader{}
	mi := &file_artifact_v1_artifact_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteArtifactHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteArtifactHeader) ProtoMessage() {}

func (x *WriteArtifactHeader) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_artifact_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteArtifactHeader.ProtoReflect.Descriptor instead.
func (*WriteArtifactHeader) Descriptor() ([]byte, []int) {
	return file_artifact_v1_artifact_proto_rawDescGZIP(), []int{2}
}

func (x *WriteArtifactHeader) GetRef() *ArtifactRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *WriteArtifactHeader) GetResume() bool {
	if x != nil {
		return x.Resume
	}
	return false
}

// WriteArtifactAck — подтверждение приёма: сервер сохранил size байт
// (после header — точка продолжения записи); committed/aborted — ответ на
// commit/abort, запись завершена.
type WriteArtifactAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Committed     bool                   `protobuf:"varint,2,opt,name=committed,proto3" json:"committed,omitempty"`
	Aborted       bool                   `protobuf:"varint,3,opt,name=aborted,proto3" json:"aborted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteArtifactAck) Reset() {
	*x = WriteArtifactAck{}
	mi := &file_artifact_v1_artifact_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteArtifactAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteArtifactAck) ProtoMessage() {}

func (x *WriteArtifactAck) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_artifact_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteArtifactAck.ProtoReflect.Descriptor instead.
func (*WriteArtifactAck) Descriptor() ([]byte, []int) {
	return file_artifact_v1_artifact_proto_rawDescGZIP(), []int{3}
}

func (x *WriteArtifactAck) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *WriteArtifactAck) GetCommitted() bool {
	if x != nil {
		return x.Committed
	}
	return false
}

func (x *WriteArtifactAck) GetAborted() bool {
	if x != nil {
		return x.Aborted
	}
	return false
}

type ReadArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *ArtifactRef           `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Follow        bool                   `protobuf:"varint,3,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadArtifactRequest) Reset() {
	*x = ReadArtifactRequest{}
	mi := &file_artifact_v1_artifact_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadArtifactRequest) ProtoMessage() {}

func (x *ReadArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_artifact_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadArtifactRequest.ProtoReflect.Descriptor instead.
func (*ReadArtifactRequest) Descriptor() ([]byte, []int) {
	return file_artifact_v1_artifact_proto_rawDescGZIP(), []int{4}
}

func (x *ReadArtifactRequest) GetRef() *ArtifactRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *ReadArtifactRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadArtifactRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type ReadArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadArtifactResponse) Reset() {
	*x = ReadArtifactResponse{}
	mi := &file_artifact_v1_artifact_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadArtifactResponse) ProtoMessage() {}

func (x *ReadArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_artifact_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadArtifactResponse.ProtoReflect.Descriptor instead.
func (*ReadArtifactResponse) Descriptor() ([]byte, []int) {
	return file_artifact_v1_artifact_proto_rawDescGZIP(), []int{5}
}

func (x *ReadArtifactResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

type StatArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *ArtifactRef           `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatArtifactRequest) Reset() {
	*x = StatArtifactRequest{}
	mi := &file_artifact_v1_artifact_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatArtifactRequest) ProtoMessage() {}

func (x *StatArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_artifact_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatArtifactRequest.ProtoReflect.Descriptor instead.
func (*StatArtifactRequest) Descriptor() ([]byte, []int) {
	return file_artifact_v1_artifact_proto_rawDescGZIP(), []int{6}
}

func (x *StatArtifactRequest) GetRef() *ArtifactRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

type StatArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         ArtifactState          `protobuf:"varint,1,opt,name=state,proto3,enum=artifact_v1.ArtifactState" json:"state,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatArtifactResponse) Reset() {
	*x = StatArtifactResponse{}
	mi := &file_artifact_v1_artifact_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatArtifactResponse) ProtoMessage() {}

func (x *StatArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_artifact_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatArtifactResponse.ProtoReflect.Descriptor instead.
func (*StatArtifactResponse) Descriptor() ([]byte, []int) {
	return file_artifact_v1_artifact_proto_rawDescGZIP(), []int{7}
}

func (x *StatArtifactResponse) GetState() ArtifactState {
	if x != nil {
		return x.State
	}
	return ArtifactState_ARTIFACT_STATE_UNSPECIFIED
}

func (x *StatArtifactResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type AbortArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *ArtifactRef           `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortArtifactRequest) Reset() {
	*x = AbortArtifactRequest{}
	mi := &file_artifact_v1_artifact_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortArtifactRequest) ProtoMessage() {}

func (x *AbortArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_artifact_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortArtifactRequest.ProtoReflect.Descriptor instead.
func (*AbortArtifactRequest) Descriptor() ([]byte, []int) {
	return file_artifact_v1_artifact_proto_rawDescGZIP(), []int{8}
}

func (x *AbortArtifactRequest) GetRef() *ArtifactRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

type AbortArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortArtifactResponse) Reset() {
	*x = AbortArtifactResponse{}
	mi := &file_artifact_v1_artifact_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortArtifactResponse) ProtoMessage() {}

func (x *AbortArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_artifact_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortArtifactResponse.ProtoReflect.Descriptor instead.
func (*AbortArtifactResponse) Descriptor() ([]byte, []int) {
	return file_artifact_v1_artifact_proto_rawDescGZIP(), []int{9}
}

type FinishAttemptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Task          string                 `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	Attempt       int32                  `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishAttemptRequest) Reset() {
	*x = FinishAttemptRequest{}
	mi := &file_artifact_v1_artifact_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishAttemptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishAttemptRequest) ProtoMessage() {}

func (x *FinishAttemptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_artifact_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishAttemptRequest.ProtoReflect.Descriptor instead.
func (*FinishAttemptRequest) Descriptor() ([]byte, []int) {
	return file_artifact_v1_artifact_proto_rawDescGZIP(), []int{10}
}

func (x *FinishAttemptRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *FinishAttemptRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *FinishAttemptRequest) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type FinishAttemptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishAttemptResponse) Reset() {
	*x = FinishAttemptResponse{}
	mi := &file_artifact_v1_artifact_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishAttemptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishAttemptResponse) ProtoMessage() {}

func (x *FinishAttemptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_artifact_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishAttemptResponse.ProtoReflect.Descriptor instead.
func (*FinishAttemptResponse) Descriptor() ([]byte, []int) {
	return file_artifact_v1_artifact_proto_rawDescGZIP(), []int{11}
}

type DeleteRunArtifactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRunArtifactsRequest) Reset() {
	*x = DeleteRunArtifactsRequest{}
	mi := &file_artifact_v1_artifact_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRunArtifactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRunArtifactsRequest) ProtoMessage() {}

func (x *DeleteRunArtifactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_artifact_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRunArtifactsRequest.ProtoReflect.Descriptor instead.
func (*DeleteRunArtifactsRequest) Descriptor() ([]byte, []int) {
	return file_artifact_v1_artifact_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteRunArtifactsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type DeleteRunArtifactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRunArtifactsResponse) Reset() {
	*x = DeleteRunArtifactsResponse{}
	mi := &file_artifact_v1_artifact_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRunArtifactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRunArtifactsResponse) ProtoMessage() {}

func (x *DeleteRunArtifactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_artifact_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRunArtifactsResponse.ProtoReflect.Descriptor instead.
func (*DeleteRunArtifactsResponse) Descriptor() ([]byte, []int) {
	return file_artifact_v1_artifact_proto_rawDescGZIP(), []int{13}
}

type ListRunArtifactsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunArtifactsRequest) Reset() {
	*x = ListRunArtifactsRequest{}
	mi := &file_artifact_v1_artifact_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunArtifactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunArtifactsRequest) ProtoMessage() {}

func (x *ListRunArtifactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_artifact_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunArtifactsRequest.ProtoReflect.Descriptor instead.
func (*ListRunArtifactsRequest) Descriptor() ([]byte, []int) {
	return file_artifact_v1_artifact_proto_rawDescGZIP(), []int{14}
}

func (x *ListRunArtifactsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type ArtifactInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Ref   *ArtifactRef           `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	State ArtifactState          `protobuf:"varint,2,opt,name=state,proto3,enum=artifact_v1.ArtifactState" json:"state,omitempty"`
	Size  int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// mtime data-файла (unix ms) — момент последней записи.
	ModifiedUnixMs int64 `protobuf:"varint,4,opt,name=modified_unix_ms,json=modifiedUnixMs,proto3" json:"modified_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ArtifactInfo) Reset() {
	*x = ArtifactInfo{}
	mi := &file_artifact_v1_artifact_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactInfo) ProtoMessage() {}

func (x *ArtifactInfo) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_artifact_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactInfo.ProtoReflect.Descriptor instead.
func (*ArtifactInfo) Descriptor() ([]byte, []int) {
	return file_artifact_v1_artifact_proto_rawDescGZIP(), []int{15}
}

func (x *ArtifactInfo) GetRef() *ArtifactRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *ArtifactInfo) GetState() ArtifactState {
	if x != nil {
		return x.State
	}
	return ArtifactState_ARTIFACT_STATE_UNSPECIFIED
}

func (x *ArtifactInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ArtifactInfo) GetModifiedUnixMs() int64 {
	if x != nil {
		return x.ModifiedUnixMs
	}
	return 0
}

type ListRunArtifactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifacts     []*ArtifactInfo        `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunArtifactsResponse) Reset() {
	*x = ListRunArtifactsResponse{}
	mi := &file_artifact_v1_artifact_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunArtifactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunArtifactsResponse) ProtoMessage() {}

func (x *ListRunArtifactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_artifact_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunArtifactsResponse.ProtoReflect.Descriptor instead.
func (*ListRunArtifactsResponse) Descriptor() ([]byte, []int) {
	return file_artifact_v1_artifact_proto_rawDescGZIP(), []int{16}
}

func (x *ListRunArtifactsResponse) GetArtifacts() []*ArtifactInfo {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type StorageStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageStatsRequest) Reset() {
	*x = StorageStatsRequest{}
	mi := &file_artifact_v1_artifact_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageStatsRequest) ProtoMessage() {}

func (x *StorageStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_artifact_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageStatsRequest.ProtoReflect.Descriptor instead.
func (*StorageStatsRequest) Descriptor() ([]byte, []int) {
	return file_artifact_v1_artifact_proto_rawDescGZIP(), []int{17}
}

// DirStats — статистика одного каталога: used — сумма размеров файлов,
// total/free — ёмкость файловой системы, на которой каталог живёт.
type DirStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsedBytes     int64                  `protobuf:"varint,1,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	TotalBytes    int64                  `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	FreeBytes     int64                  `protobuf:"varint,3,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirStats) Reset() {
	*x = DirStats{}
	mi := &file_artifact_v1_artifact_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirStats) ProtoMessage() {}

func (x *DirStats) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_artifact_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirStats.ProtoReflect.Descriptor instead.
func (*DirStats) Descriptor() ([]byte, []int) {
	return file_artifact_v1_artifact_proto_rawDescGZIP(), []int{18}
}

func (x *DirStats) GetUsedBytes() int64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *DirStats) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *DirStats) GetFreeBytes() int64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

type StorageStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *DirStats              `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // DATA_DIR — артефакты
	Logs          *DirStats              `protobuf:"bytes,2,opt,name=logs,proto3" json:"logs,omitempty"` // LOG_DIR — логи тасков
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageStatsResponse) Reset() {
	*x = StorageStatsResponse{}
	mi := &file_artifact_v1_artifact_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageStatsResponse) ProtoMessage() {}

func (x *StorageStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_artifact_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageStatsResponse.ProtoReflect.Descriptor instead.
func (*StorageStatsResponse) Descriptor() ([]byte, []int) {
	return file_artifact_v1_artifact_proto_rawDescGZIP(), []int{19}
}

func (x *StorageStatsResponse) GetData() *DirStats {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StorageStatsResponse) GetLogs() *DirStats {
	if x != nil {
		return x.Logs
	}
	return nil
}

var File_artifact_v1_artifact_proto protoreflect.FileDescriptor

const file_artifact_v1_artifact_proto_rawDesc = "" +
	"\n" +
	"\x1aartifact_v1/artifact.proto\x12\vartifact_v1\"f\n" +
	"\vArtifactRef\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x12\n" +
	"\x04task\x18\x02 \x01(\tR\x04task\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x05R\aattempt\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"\xa3\x01\n" +
	"\x14WriteArtifactRequest\x12:\n" +
	"\x06header\x18\x01 \x01(\v2 .artifact_v1.WriteArtifactHeaderH\x00R\x06header\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunk\x12\x18\n" +
	"\x06commit\x18\x03 \x01(\bH\x00R\x06commit\x12\x16\n" +
	"\x05abort\x18\x04 \x01(\bH\x00R\x05abortB\x05\n" +
	"\x03msg\"Y\n" +
	"\x13WriteArtifactHeader\x12*\n" +
	"\x03ref\x18\x01 \x01(\v2\x18.artifact_v1.ArtifactRefR\x03ref\x12\x16\n" +
	"\x06resume\x18\x02 \x01(\bR\x06resume\"^\n" +
	"\x10WriteArtifactAck\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\x12\x1c\n" +
	"\tcommitted\x18\x02 \x01(\bR\tcommitted\x12\x18\n" +
	"\aaborted\x18\x03 \x01(\bR\aaborted\"q\n" +
	"\x13ReadArtifactRequest\x12*\n" +
	"\x03ref\x18\x01 \x01(\v2\x18.artifact_v1.ArtifactRefR\x03ref\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06follow\x18\x03 \x01(\bR\x06follow\",\n" +
	"\x14ReadArtifactResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"A\n" +
	"\x13StatArtifactRequest\x12*\n" +
	"\x03ref\x18\x01 \x01(\v2\x18.artifact_v1.ArtifactRefR\x03ref\"\\\n" +
	"\x14StatArtifactResponse\x120\n" +
	"\x05state\x18\x01 \x01(\x0e2\x1a.artifact_v1.ArtifactStateR\x05state\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"B\n" +
	"\x14AbortArtifactRequest\x12*\n" +
	"\x03ref\x18\x01 \x01(\v2\x18.artifact_v1.ArtifactRefR\x03ref\"\x17\n" +
	"\x15AbortArtifactResponse\"[\n" +
	"\x14FinishAttemptRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x12\n" +
	"\x04task\x18\x02 \x01(\tR\x04task\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x05R\aattempt\"\x17\n" +
	"\x15FinishAttemptResponse\"2\n" +
	"\x19DeleteRunArtifactsRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\x1c\n" +
	"\x1aDeleteRunArtifactsResponse\"0\n" +
	"\x17ListRunArtifactsRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\xaa\x01\n" +
	"\fArtifactInfo\x12*\n" +
	"\x03ref\x18\x01 \x01(\v2\x18.artifact_v1.ArtifactRefR\x03ref\x120\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1a.artifact_v1.ArtifactStateR\x05state\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12(\n" +
	"\x10modified_unix_ms\x18\x04 \x01(\x03R\x0emodifiedUnixMs\"S\n" +
	"\x18ListRunArtifactsResponse\x127\n" +
	"\tartifacts\x18\x01 \x03(\v2\x19.artifact_v1.ArtifactInfoR\tartifacts\"\x15\n" +
	"\x13StorageStatsRequest\"i\n" +
	"\bDirStats\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x01 \x01(\x03R\tusedBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x03R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x03 \x01(\x03R\tfreeBytes\"l\n" +
	"\x14StorageStatsResponse\x12)\n" +
	"\x04data\x18\x01 \x01(\v2\x15.artifact_v1.DirStatsR\x04data\x12)\n" +
	"\x04logs\x18\x02 \x01(\v2\x15.artifact_v1.DirStatsR\x04logs*\x85\x01\n" +
	"\rArtifactState\x12\x1e\n" +
	"\x1aARTIFACT_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ARTIFACT_STATE_WRITING\x10\x01\x12\x1c\n" +
	"\x18ARTIFACT_STATE_COMMITTED\x10\x02\x12\x1a\n" +
	"\x16ARTIFACT_STATE_ABORTED\x10\x032\xe4\x05\n" +
	"\x0fArtifactService\x12U\n" +
	"\rWriteArtifact\x12!.artifact_v1.WriteArtifactRequest\x1a\x1d.artifact_v1.WriteArtifactAck(\x010\x01\x12U\n" +
	"\fReadArtifact\x12 .artifact_v1.ReadArtifactRequest\x1a!.artifact_v1.ReadArtifactResponse0\x01\x12S\n" +
	"\fStatArtifact\x12 .artifact_v1.StatArtifactRequest\x1a!.artifact_v1.StatArtifactResponse\x12V\n" +
	"\rAbortArtifact\x12!.artifact_v1.AbortArtifactRequest\x1a\".artifact_v1.AbortArtifactResponse\x12V\n" +
	"\rFinishAttempt\x12!.artifact_v1.FinishAttemptRequest\x1a\".artifact_v1.FinishAttemptResponse\x12e\n" +
	"\x12DeleteRunArtifacts\x12&.artifact_v1.DeleteRunArtifactsRequest\x1a'.artifact_v1.DeleteRunArtifactsResponse\x12_\n" +
	"\x10ListRunArtifacts\x12$.artifact_v1.ListRunArtifactsRequest\x1a%.artifact_v1.ListRunArtifactsResponse\x12V\n" +
	"\x0fGetStorageStats\x12 .artifact_v1.StorageStatsRequest\x1a!.artifact_v1.StorageStatsResponseB4Z2github.com/rendau/loom/api/artifact_v1;artifact_v1b\x06proto3"

var (
	file_artifact_v1_artifact_proto_rawDescOnce sync.Once
	file_artifact_v1_artifact_proto_rawDescData []byte
)

func file_artifact_v1_artifact_proto_rawDescGZIP() []byte {
	file_artifact_v1_artifact_proto_rawDescOnce.Do(func() {
		file_artifact_v1_artifact_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_artifact_v1_artifact_proto_rawDesc), len(file_artifact_v1_artifact_proto_rawDesc)))
	})
	return file_artifact_v1_artifact_proto_rawDescData
}

var file_artifact_v1_artifact_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_artifact_v1_artifact_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_artifact_v1_artifact_proto_goTypes = []any{
	(ArtifactState)(0),                 // 0: artifact_v1.ArtifactState
	(*ArtifactRef)(nil),                // 1: artifact_v1.ArtifactRef
	(*WriteArtifactRequest)(nil),       // 2: artifact_v1.WriteArtifactRequest
	(*WriteArtifactHeader)(nil),        // 3: artifact_v1.WriteArtifactHeader
	(*WriteArtifactAck)(nil),           // 4: artifact_v1.WriteArtifactAck
	(*ReadArtifactRequest)(nil),        // 5: artifact_v1.ReadArtifactRequest
	(*ReadArtifactResponse)(nil),       // 6: artifact_v1.ReadArtifactResponse
	(*StatArtifactRequest)(nil),        // 7: artifact_v1.StatArtifactRequest
	(*StatArtifactResponse)(nil),       // 8: artifact_v1.StatArtifactResponse
	(*AbortArtifactRequest)(nil),       // 9: artifact_v1.AbortArtifactRequest
	(*AbortArtifactResponse)(nil),      // 10: artifact_v1.AbortArtifactResponse
	(*FinishAttemptRequest)(nil),       // 11: artifact_v1.FinishAttemptRequest
	(*FinishAttemptResponse)(nil),      // 12: artifact_v1.FinishAttemptResponse
	(*DeleteRunArtifactsRequest)(nil),  // 13: artifact_v1.DeleteRunArtifactsRequest
	(*DeleteRunArtifactsResponse)(nil), // 14: artifact_v1.DeleteRunArtifactsResponse
	(*ListRunArtifactsRequest)(nil),    // 15: artifact_v1.ListRunArtifactsRequest
	(*ArtifactInfo)(nil),               // 16: artifact_v1.ArtifactInfo
	(*ListRunArtifactsResponse)(nil),   // 17: artifact_v1.ListRunArtifactsResponse
	(*StorageStatsRequest)(nil),        // 18: artifact_v1.StorageStatsRequest
	(*DirStats)(nil),                   // 19: artifact_v1.DirStats
	(*StorageStatsResponse)(nil),       // 20: artifact_v1.StorageStatsResponse
}
var file_artifact_v1_artifact_proto_depIdxs = []int32{
	3,  // 0: artifact_v1.WriteArtifactRequest.header:type_name -> artifact_v1.WriteArtifactHeader
	1,  // 1: artifact_v1.WriteArtifactHeader.ref:type_name -> artifact_v1.ArtifactRef
	1,  // 2: artifact_v1.ReadArtifactRequest.ref:type_name -> artifact_v1.ArtifactRef
	1,  // 3: artifact_v1.StatArtifactRequest.ref:type_name -> artifact_v1.ArtifactRef
	0,  // 4: artifact_v1.StatArtifactResponse.state:type_name -> artifact_v1.ArtifactState
	1,  // 5: artifact_v1.AbortArtifactRequest.ref:type_name -> artifact_v1.ArtifactRef
	1,  // 6: artifact_v1.ArtifactInfo.ref:type_name -> artifact_v1.ArtifactRef
	0,  // 7: artifact_v1.ArtifactInfo.state:type_name -> artifact_v1.ArtifactState
	16, // 8: artifact_v1.ListRunArtifactsResponse.artifacts:type_name -> artifact_v1.ArtifactInfo
	19, // 9: artifact_v1.StorageStatsResponse.data:type_name -> artifact_v1.DirStats
	19, // 10: artifact_v1.StorageStatsResponse.logs:type_name -> artifact_v1.DirStats
	2,  // 11: artifact_v1.ArtifactService.WriteArtifact:input_type -> artifact_v1.WriteArtifactRequest
	5,  // 12: artifact_v1.ArtifactService.ReadArtifact:input_type -> artifact_v1.ReadArtifactRequest
	7,  // 13: artifact_v1.ArtifactService.StatArtifact:input_type -> artifact_v1.StatArtifactRequest
	9,  // 14: artifact_v1.ArtifactService.AbortArtifact:input_type -> artifact_v1.AbortArtifactRequest
	11, // 15: artifact_v1.ArtifactService.FinishAttempt:input_type -> artifact_v1.FinishAttemptRequest
	13, // 16: artifact_v1.ArtifactService.DeleteRunArtifacts:input_type -> artifact_v1.DeleteRunArtifactsRequest
	15, // 17: artifact_v1.ArtifactService.ListRunArtifacts:input_type -> artifact_v1.ListRunArtifactsRequest
	18, // 18: artifact_v1.ArtifactService.GetStorageStats:input_type -> artifact_v1.StorageStatsRequest
	4,  // 19: artifact_v1.ArtifactService.WriteArtifact:output_type -> artifact_v1.WriteArtifactAck
	6,  // 20: artifact_v1.ArtifactService.ReadArtifact:output_type -> artifact_v1.ReadArtifactResponse
	8,  // 21: artifact_v1.ArtifactService.StatArtifact:output_type -> artifact_v1.StatArtifactResponse
	10, // 22: artifact_v1.ArtifactService.AbortArtifact:output_type -> artifact_v1.AbortArtifactResponse
	12, // 23: artifact_v1.ArtifactService.FinishAttempt:output_type -> artifact_v1.FinishAttemptResponse
	14, // 24: artifact_v1.ArtifactService.DeleteRunArtifacts:output_type -> artifact_v1.DeleteRunArtifactsResponse
	17, // 25: artifact_v1.ArtifactService.ListRunArtifacts:output_type -> artifact_v1.ListRunArtifactsResponse
	20, // 26: artifact_v1.ArtifactService.GetStorageStats:output_type -> artifact_v1.StorageStatsResponse
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_artifact_v1_artifact_proto_init() }
func file_artifact_v1_artifact_proto_init() {
	if File_artifact_v1_artifact_proto != nil {
		return
	}
	file_artifact_v1_artifact_proto_msgTypes[1].OneofWrappers = []any{
		(*WriteArtifactRequest_Header)(nil),
		(*WriteArtifactRequest_Chunk)(nil),
		(*WriteArtifactRequest_Commit)(nil),
		(*WriteArtifactRequest_Abort)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_artifact_v1_artifact_proto_rawDesc), len(file_artifact_v1_artifact_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_artifact_v1_artifact_proto_goTypes,
		DependencyIndexes: file_artifact_v1_artifact_proto_depIdxs,
		EnumInfos:         file_artifact_v1_artifact_proto_enumTypes,
		MessageInfos:      file_artifact_v1_artifact_proto_msgTypes,
	}.Build()
	File_artifact_v1_artifact_proto = out.File
	file_artifact_v1_artifact_proto_goTypes = nil
	file_artifact_v1_artifact_proto_depIdxs = nil
}
