// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: artifact_v1/task_log.proto

package artifact_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TaskLogSource — происхождение строки: структурный логгер Runtime,
// перехваченные file descriptor'ы процесса (туда пишут паники Go-рантайма
// и сторонние библиотеки мимо логгера) или сам control plane (исход
// попытки, причина смерти пода).
type TaskLogSource int32

const (
	TaskLogSource_TASK_LOG_SOURCE_UNSPECIFIED TaskLogSource = 0
	TaskLogSource_TASK_LOG_SOURCE_LOG         TaskLogSource = 1
	TaskLogSource_TASK_LOG_SOURCE_STDOUT      TaskLogSource = 2
	TaskLogSource_TASK_LOG_SOURCE_STDERR      TaskLogSource = 3
	TaskLogSource_TASK_LOG_SOURCE_SERVER      TaskLogSource = 4
)

// Enum value maps for TaskLogSource.
var (
	TaskLogSource_name = map[int32]string{
		0: "TASK_LOG_SOURCE_UNSPECIFIED",
		1: "TASK_LOG_SOURCE_LOG",
		2: "TASK_LOG_SOURCE_STDOUT",
		3: "TASK_LOG_SOURCE_STDERR",
		4: "TASK_LOG_SOURCE_SERVER",
	}
	TaskLogSource_value = map[string]int32{
		"TASK_LOG_SOURCE_UNSPECIFIED": 0,
		"TASK_LOG_SOURCE_LOG":         1,
		"TASK_LOG_SOURCE_STDOUT":      2,
		"TASK_LOG_SOURCE_STDERR":      3,
		"TASK_LOG_SOURCE_SERVER":      4,
	}
)

func (x TaskLogSource) Enum() *TaskLogSource {
	p := new(TaskLogSource)
	*p = x
	return p
}

func (x TaskLogSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskLogSource) Descriptor() protoreflect.EnumDescriptor {
	return file_artifact_v1_task_log_proto_enumTypes[0].Descriptor()
}

func (TaskLogSource) Type() protoreflect.EnumType {
	return &file_artifact_v1_task_log_proto_enumTypes[0]
}

func (x TaskLogSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskLogSource.Descriptor instead.
func (TaskLogSource) EnumDescriptor() ([]byte, []int) {
	return file_artifact_v1_task_log_proto_rawDescGZIP(), []int{0}
}

type PushTaskLogRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*PushTaskLogRequest_Header
	//	*PushTaskLogRequest_Batch
	Msg           isPushTaskLogRequest_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushTaskLogRequest) Reset() {
	*x = PushTaskLogRequest{}
	mi := &file_artifact_v1_task_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushTaskLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushTaskLogRequest) ProtoMessage() {}

func (x *PushTaskLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_task_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushTaskLogRequest.ProtoReflect.Descriptor instead.
func (*PushTaskLogRequest) Descriptor() ([]byte, []int) {
	return file_artifact_v1_task_log_proto_rawDescGZIP(), []int{0}
}

func (x *PushTaskLogRequest) GetMsg() isPushTaskLogRequest_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *PushTaskLogRequest) GetHeader() *TaskLogHeader {
	if x != nil {
		if x, ok := x.Msg.(*PushTaskLogRequest_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *PushTaskLogRequest) GetBatch() *TaskLogBatch {
	if x != nil {
		if x, ok := x.Msg.(*PushTaskLogRequest_Batch); ok {
			return x.Batch
		}
	}
	return nil
}

type isPushTaskLogRequest_Msg interface {
	isPushTaskLogRequest_Msg()
}

type PushTaskLogRequest_Header struct {
	Header *TaskLogHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type PushTaskLogRequest_Batch struct {
	Batch *TaskLogBatch `protobuf:"bytes,2,opt,name=batch,proto3,oneof"`
}

func (*PushTaskLogRequest_Header) isPushTaskLogRequest_Msg() {}

func (*PushTaskLogRequest_Batch) isPushTaskLogRequest_Msg() {}

// PushTaskLogAck — подтверждение приёма: сервер сохранил все строки с
// seq < next_seq.
type PushTaskLogAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextSeq       int64                  `protobuf:"varint,1,opt,name=next_seq,json=nextSeq,proto3" json:"next_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushTaskLogAck) Reset() {
	*x = PushTaskLogAck{}
	mi := &file_artifact_v1_task_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushTaskLogAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushTaskLogAck) ProtoMessage() {}

func (x *PushTaskLogAck) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_task_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushTaskLogAck.ProtoReflect.Descriptor instead.
func (*PushTaskLogAck) Descriptor() ([]byte, []int) {
	return file_artifact_v1_task_log_proto_rawDescGZIP(), []int{1}
}

func (x *PushTaskLogAck) GetNextSeq() int64 {
	if x != nil {
		return x.NextSeq
	}
	return 0
}

type TaskLogHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Task          string                 `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	Attempt       int32                  `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskLogHeader) Reset() {
	*x = TaskLogHeader{}
	mi := &file_artifact_v1_task_log_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLogHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLogHeader) ProtoMessage() {}

func (x *TaskLogHeader) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_task_log_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLogHeader.ProtoReflect.Descriptor instead.
func (*TaskLogHeader) Descriptor() ([]byte, []int) {
	return file_artifact_v1_task_log_proto_rawDescGZIP(), []int{2}
}

func (x *TaskLogHeader) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TaskLogHeader) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *TaskLogHeader) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

type TaskLogBatch struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// first_seq — номер первой строки батча (сквозная нумерация строк
	// попытки клиентом, с нуля).
	FirstSeq      int64           `protobuf:"varint,1,opt,name=first_seq,json=firstSeq,proto3" json:"first_seq,omitempty"`
	Entries       []*TaskLogEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskLogBatch) Reset() {
	*x = TaskLogBatch{}
	mi := &file_artifact_v1_task_log_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLogBatch) ProtoMessage() {}

func (x *TaskLogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_task_log_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLogBatch.ProtoReflect.Descriptor instead.
func (*TaskLogBatch) Descriptor() ([]byte, []int) {
	return file_artifact_v1_task_log_proto_rawDescGZIP(), []int{3}
}

func (x *TaskLogBatch) GetFirstSeq() int64 {
	if x != nil {
		return x.FirstSeq
	}
	return 0
}

func (x *TaskLogBatch) GetEntries() []*TaskLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type TaskLogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TsUnixMs      int64                  `protobuf:"varint,1,opt,name=ts_unix_ms,json=tsUnixMs,proto3" json:"ts_unix_ms,omitempty"`
	Source        TaskLogSource          `protobuf:"varint,2,opt,name=source,proto3,enum=artifact_v1.TaskLogSource" json:"source,omitempty"`
	Line          string                 `protobuf:"bytes,3,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskLogEntry) Reset() {
	*x = TaskLogEntry{}
	mi := &file_artifact_v1_task_log_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLogEntry) ProtoMessage() {}

func (x *TaskLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_task_log_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLogEntry.ProtoReflect.Descriptor instead.
func (*TaskLogEntry) Descriptor() ([]byte, []int) {
	return file_artifact_v1_task_log_proto_rawDescGZIP(), []int{4}
}

func (x *TaskLogEntry) GetTsUnixMs() int64 {
	if x != nil {
		return x.TsUnixMs
	}
	return 0
}

func (x *TaskLogEntry) GetSource() TaskLogSource {
	if x != nil {
		return x.Source
	}
	return TaskLogSource_TASK_LOG_SOURCE_UNSPECIFIED
}

func (x *TaskLogEntry) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

type ReadTaskLogRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	RunId   string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Task    string                 `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	Attempt int32                  `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// after_seq — сколько первых строк пропустить (для реконнекта читателя).
	AfterSeq      int64 `protobuf:"varint,4,opt,name=after_seq,json=afterSeq,proto3" json:"after_seq,omitempty"`
	Follow        bool  `protobuf:"varint,5,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTaskLogRequest) Reset() {
	*x = ReadTaskLogRequest{}
	mi := &file_artifact_v1_task_log_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTaskLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTaskLogRequest) ProtoMessage() {}

func (x *ReadTaskLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_task_log_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTaskLogRequest.ProtoReflect.Descriptor instead.
func (*ReadTaskLogRequest) Descriptor() ([]byte, []int) {
	return file_artifact_v1_task_log_proto_rawDescGZIP(), []int{5}
}

func (x *ReadTaskLogRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ReadTaskLogRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *ReadTaskLogRequest) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *ReadTaskLogRequest) GetAfterSeq() int64 {
	if x != nil {
		return x.AfterSeq
	}
	return 0
}

func (x *ReadTaskLogRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type ReadTaskLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*TaskLogEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadTaskLogResponse) Reset() {
	*x = ReadTaskLogResponse{}
	mi := &file_artifact_v1_task_log_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadTaskLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadTaskLogResponse) ProtoMessage() {}

func (x *ReadTaskLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_task_log_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadTaskLogResponse.ProtoReflect.Descriptor instead.
func (*ReadTaskLogResponse) Descriptor() ([]byte, []int) {
	return file_artifact_v1_task_log_proto_rawDescGZIP(), []int{6}
}

func (x *ReadTaskLogResponse) GetEntries() []*TaskLogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type FinishTaskLogRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	RunId   string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Task    string                 `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	Attempt int32                  `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// final — финальные строки от control plane (исход попытки); дописываются
	// перед commit.
	Final         []*TaskLogEntry `protobuf:"bytes,4,rep,name=final,proto3" json:"final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishTaskLogRequest) Reset() {
	*x = FinishTaskLogRequest{}
	mi := &file_artifact_v1_task_log_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishTaskLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishTaskLogRequest) ProtoMessage() {}

func (x *FinishTaskLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_task_log_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishTaskLogRequest.ProtoReflect.Descriptor instead.
func (*FinishTaskLogRequest) Descriptor() ([]byte, []int) {
	return file_artifact_v1_task_log_proto_rawDescGZIP(), []int{7}
}

func (x *FinishTaskLogRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *FinishTaskLogRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *FinishTaskLogRequest) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *FinishTaskLogRequest) GetFinal() []*TaskLogEntry {
	if x != nil {
		return x.Final
	}
	return nil
}

type FinishTaskLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishTaskLogResponse) Reset() {
	*x = FinishTaskLogResponse{}
	mi := &file_artifact_v1_task_log_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishTaskLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishTaskLogResponse) ProtoMessage() {}

func (x *FinishTaskLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_task_log_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishTaskLogResponse.ProtoReflect.Descriptor instead.
func (*FinishTaskLogResponse) Descriptor() ([]byte, []int) {
	return file_artifact_v1_task_log_proto_rawDescGZIP(), []int{8}
}

type DeleteRunTaskLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRunTaskLogsRequest) Reset() {
	*x = DeleteRunTaskLogsRequest{}
	mi := &file_artifact_v1_task_log_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRunTaskLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRunTaskLogsRequest) ProtoMessage() {}

func (x *DeleteRunTaskLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_task_log_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRunTaskLogsRequest.ProtoReflect.Descriptor instead.
func (*DeleteRunTaskLogsRequest) Descriptor() ([]byte, []int) {
	return file_artifact_v1_task_log_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteRunTaskLogsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type DeleteRunTaskLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRunTaskLogsResponse) Reset() {
	*x = DeleteRunTaskLogsResponse{}
	mi := &file_artifact_v1_task_log_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRunTaskLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRunTaskLogsResponse) ProtoMessage() {}

func (x *DeleteRunTaskLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_artifact_v1_task_log_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRunTaskLogsResponse.ProtoReflect.Descriptor instead.
func (*DeleteRunTaskLogsResponse) Descriptor() ([]byte, []int) {
	return file_artifact_v1_task_log_proto_rawDescGZIP(), []int{10}
}

var File_artifact_v1_task_log_proto protoreflect.FileDescriptor

const file_artifact_v1_task_log_proto_rawDesc = "" +
	"\n" +
	"\x1aartifact_v1/task_log.proto\x12\vartifact_v1\"\x84\x01\n" +
	"\x12PushTaskLogRequest\x124\n" +
	"\x06header\x18\x01 \x01(\v2\x1a.artifact_v1.TaskLogHeaderH\x00R\x06header\x121\n" +
	"\x05batch\x18\x02 \x01(\v2\x19.artifact_v1.TaskLogBatchH\x00R\x05batchB\x05\n" +
	"\x03msg\"+\n" +
	"\x0ePushTaskLogAck\x12\x19\n" +
	"\bnext_seq\x18\x01 \x01(\x03R\anextSeq\"T\n" +
	"\rTaskLogHeader\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x12\n" +
	"\x04task\x18\x02 \x01(\tR\x04task\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x05R\aattempt\"`\n" +
	"\fTaskLogBatch\x12\x1b\n" +
	"\tfirst_seq\x18\x01 \x01(\x03R\bfirstSeq\x123\n" +
	"\aentries\x18\x02 \x03(\v2\x19.artifact_v1.TaskLogEntryR\aentries\"t\n" +
	"\fTaskLogEntry\x12\x1c\n" +
	"\n" +
	"ts_unix_ms\x18\x01 \x01(\x03R\btsUnixMs\x122\n" +
	"\x06source\x18\x02 \x01(\x0e2\x1a.artifact_v1.TaskLogSourceR\x06source\x12\x12\n" +
	"\x04line\x18\x03 \x01(\tR\x04line\"\x8e\x01\n" +
	"\x12ReadTaskLogRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x12\n" +
	"\x04task\x18\x02 \x01(\tR\x04task\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x05R\aattempt\x12\x1b\n" +
	"\tafter_seq\x18\x04 \x01(\x03R\bafterSeq\x12\x16\n" +
	"\x06follow\x18\x05 \x01(\bR\x06follow\"J\n" +
	"\x13ReadTaskLogResponse\x123\n" +
	"\aentries\x18\x01 \x03(\v2\x19.artifact_v1.TaskLogEntryR\aentries\"\x8c\x01\n" +
	"\x14FinishTaskLogRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x12\n" +
	"\x04task\x18\x02 \x01(\tR\x04task\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x05R\aattempt\x12/\n" +
	"\x05final\x18\x04 \x03(\v2\x19.artifact_v1.TaskLogEntryR\x05final\"\x17\n" +
	"\x15FinishTaskLogResponse\"1\n" +
	"\x18DeleteRunTaskLogsRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\x1b\n" +
	"\x19DeleteRunTaskLogsResponse*\x9d\x01\n" +
	"\rTaskLogSource\x12\x1f\n" +
	"\x1bTASK_LOG_SOURCE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13TASK_LOG_SOURCE_LOG\x10\x01\x12\x1a\n" +
	"\x16TASK_LOG_SOURCE_STDOUT\x10\x02\x12\x1a\n" +
	"\x16TASK_LOG_SOURCE_STDERR\x10\x03\x12\x1a\n" +
	"\x16TASK_LOG_SOURCE_SERVER\x10\x042\xf1\x02\n" +
	"\x0eTaskLogService\x12O\n" +
	"\vPushTaskLog\x12\x1f.artifact_v1.PushTaskLogRequest\x1a\x1b.artifact_v1.PushTaskLogAck(\x010\x01\x12R\n" +
	"\vReadTaskLog\x12\x1f.artifact_v1.ReadTaskLogRequest\x1a .artifact_v1.ReadTaskLogResponse0\x01\x12V\n" +
	"\rFinishTaskLog\x12!.artifact_v1.FinishTaskLogRequest\x1a\".artifact_v1.FinishTaskLogResponse\x12b\n" +
	"\x11DeleteRunTaskLogs\x12%.artifact_v1.DeleteRunTaskLogsRequest\x1a&.artifact_v1.DeleteRunTaskLogsResponseB4Z2github.com/rendau/loom/api/artifact_v1;artifact_v1b\x06proto3"

var (
	file_artifact_v1_task_log_proto_rawDescOnce sync.Once
	file_artifact_v1_task_log_proto_rawDescData []byte
)

func file_artifact_v1_task_log_proto_rawDescGZIP() []byte {
	file_artifact_v1_task_log_proto_rawDescOnce.Do(func() {
		file_artifact_v1_task_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_artifact_v1_task_log_proto_rawDesc), len(file_artifact_v1_task_log_proto_rawDesc)))
	})
	return file_artifact_v1_task_log_proto_rawDescData
}

var file_artifact_v1_task_log_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_artifact_v1_task_log_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_artifact_v1_task_log_proto_goTypes = []any{
	(TaskLogSource)(0),                // 0: artifact_v1.TaskLogSource
	(*PushTaskLogRequest)(nil),        // 1: artifact_v1.PushTaskLogRequest
	(*PushTaskLogAck)(nil),            // 2: artifact_v1.PushTaskLogAck
	(*TaskLogHeader)(nil),             // 3: artifact_v1.TaskLogHeader
	(*TaskLogBatch)(nil),              // 4: artifact_v1.TaskLogBatch
	(*TaskLogEntry)(nil),              // 5: artifact_v1.TaskLogEntry
	(*ReadTaskLogRequest)(nil),        // 6: artifact_v1.ReadTaskLogRequest
	(*ReadTaskLogResponse)(nil),       // 7: artifact_v1.ReadTaskLogResponse
	(*FinishTaskLogRequest)(nil),      // 8: artifact_v1.FinishTaskLogRequest
	(*FinishTaskLogResponse)(nil),     // 9: artifact_v1.FinishTaskLogResponse
	(*DeleteRunTaskLogsRequest)(nil),  // 10: artifact_v1.DeleteRunTaskLogsRequest
	(*DeleteRunTaskLogsResponse)(nil), // 11: artifact_v1.DeleteRunTaskLogsResponse
}
var file_artifact_v1_task_log_proto_depIdxs = []int32{
	3,  // 0: artifact_v1.PushTaskLogRequest.header:type_name -> artifact_v1.TaskLogHeader
	4,  // 1: artifact_v1.PushTaskLogRequest.batch:type_name -> artifact_v1.TaskLogBatch
	5,  // 2: artifact_v1.TaskLogBatch.entries:type_name -> artifact_v1.TaskLogEntry
	0,  // 3: artifact_v1.TaskLogEntry.source:type_name -> artifact_v1.TaskLogSource
	5,  // 4: artifact_v1.ReadTaskLogResponse.entries:type_name -> artifact_v1.TaskLogEntry
	5,  // 5: artifact_v1.FinishTaskLogRequest.final:type_name -> artifact_v1.TaskLogEntry
	1,  // 6: artifact_v1.TaskLogService.PushTaskLog:input_type -> artifact_v1.PushTaskLogRequest
	6,  // 7: artifact_v1.TaskLogService.ReadTaskLog:input_type -> artifact_v1.ReadTaskLogRequest
	8,  // 8: artifact_v1.TaskLogService.FinishTaskLog:input_type -> artifact_v1.FinishTaskLogRequest
	10, // 9: artifact_v1.TaskLogService.DeleteRunTaskLogs:input_type -> artifact_v1.DeleteRunTaskLogsRequest
	2,  // 10: artifact_v1.TaskLogService.PushTaskLog:output_type -> artifact_v1.PushTaskLogAck
	7,  // 11: artifact_v1.TaskLogService.ReadTaskLog:output_type -> artifact_v1.ReadTaskLogResponse
	9,  // 12: artifact_v1.TaskLogService.FinishTaskLog:output_type -> artifact_v1.FinishTaskLogResponse
	11, // 13: artifact_v1.TaskLogService.DeleteRunTaskLogs:output_type -> artifact_v1.DeleteRunTaskLogsResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_artifact_v1_task_log_proto_init() }
func file_artifact_v1_task_log_proto_init() {
	if File_artifact_v1_task_log_proto != nil {
		return
	}
	file_artifact_v1_task_log_proto_msgTypes[0].OneofWrappers = []any{
		(*PushTaskLogRequest_Header)(nil),
		(*PushTaskLogRequest_Batch)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_artifact_v1_task_log_proto_rawDesc), len(file_artifact_v1_task_log_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_artifact_v1_task_log_proto_goTypes,
		DependencyIndexes: file_artifact_v1_task_log_proto_depIdxs,
		EnumInfos:         file_artifact_v1_task_log_proto_enumTypes,
		MessageInfos:      file_artifact_v1_task_log_proto_msgTypes,
	}.Build()
	File_artifact_v1_task_log_proto = out.File
	file_artifact_v1_task_log_proto_goTypes = nil
	file_artifact_v1_task_log_proto_depIdxs = nil
}
